import type { SubscriptionPlanId } from "@/lib/subscription/types"

export type TokenPricingTier = "low" | "mid" | "high"

export type TokenFeatureComplexity = "simple" | "moderate" | "heavy"

export type TokenPricingMatrixEntry = {
  code: string
  category: "ai_feature" | "commissioner_function"
  featureLabel: string
  description: string
  tier: TokenPricingTier
  complexity: TokenFeatureComplexity
  tokenCost: number
  requiredPlan: SubscriptionPlanId | null
}

/**
 * PROMPT 254 — Central token pricing matrix.
 * Whole-number token costs by relative compute + scope + user value.
 */
export const TOKEN_SPEND_RULE_MATRIX: readonly TokenPricingMatrixEntry[] = [
  // Low-cost features
  {
    code: "ai_player_comparison_quick_explanation",
    category: "ai_feature",
    featureLabel: "Quick player comparison explanation",
    description: "Fast side-by-side player comparison summary.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "ai_waiver_one_off_suggestion",
    category: "ai_feature",
    featureLabel: "One-off waiver suggestion",
    description: "Single waiver add/drop recommendation.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "ai_matchup_explanation_single",
    category: "ai_feature",
    featureLabel: "One matchup explanation",
    description: "Single matchup confidence explanation.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "ai_start_sit_explanation_single",
    category: "ai_feature",
    featureLabel: "One start/sit explanation",
    description: "Single start/sit recommendation explanation.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "ai_lineup_recommendation_explanation_single",
    category: "ai_feature",
    featureLabel: "One lineup recommendation explanation",
    description: "Single lineup recommendation reasoning.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },

  // Mid-cost features
  {
    code: "ai_trade_analyzer_full_review",
    category: "ai_feature",
    featureLabel: "Trade analyzer full review",
    description: "Full trade context + fairness + action plan review.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 3,
    requiredPlan: "pro",
  },
  {
    code: "ai_draft_helper_session_recommendation",
    category: "ai_feature",
    featureLabel: "Draft helper session recommendation",
    description: "Session-level draft recommendation flow.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 3,
    requiredPlan: "war_room",
  },
  {
    code: "ai_draft_pick_explanation",
    category: "ai_feature",
    featureLabel: "Draft pick explanation",
    description: "Single pick explanation with contextual tradeoffs.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "war_room",
  },
  {
    code: "ai_weekly_planning_session",
    category: "ai_feature",
    featureLabel: "Weekly AI planning session",
    description: "Weekly multi-step planning guidance.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 3,
    requiredPlan: "pro",
  },
  {
    code: "ai_league_rankings_explanation",
    category: "ai_feature",
    featureLabel: "League rankings explanation",
    description: "Rankings interpretation with explainable context.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "commissioner",
  },
  {
    code: "ai_draft_rankings_explanation",
    category: "ai_feature",
    featureLabel: "Draft rankings explanation",
    description: "Draft ranking context and strategic implications.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "war_room",
  },

  // High-cost features
  {
    code: "ai_war_room_multi_step_planning",
    category: "ai_feature",
    featureLabel: "Multi-step war room planning",
    description: "Extended multi-step draft war room planning.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 6,
    requiredPlan: "war_room",
  },
  {
    code: "ai_strategy_3_5_year_planning",
    category: "ai_feature",
    featureLabel: "3-5 year strategy planning",
    description: "Long-horizon 3-5 year strategic planning output.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 7,
    requiredPlan: "war_room",
  },
  {
    code: "ai_storyline_creation",
    category: "commissioner_function",
    featureLabel: "AI storyline creation",
    description: "League storyline generation with narrative synthesis.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 5,
    requiredPlan: "commissioner",
  },
  {
    code: "commissioner_ai_collusion_detection_scan",
    category: "commissioner_function",
    featureLabel: "AI collusion detection scan",
    description: "League-wide collusion signal analysis scan.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 8,
    requiredPlan: "commissioner",
  },
  {
    code: "commissioner_ai_tanking_detection_scan",
    category: "commissioner_function",
    featureLabel: "AI tanking detection scan",
    description: "League-wide tanking signal analysis scan.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 7,
    requiredPlan: "commissioner",
  },
  {
    code: "commissioner_ai_team_manager_actions",
    category: "commissioner_function",
    featureLabel: "AI team manager actions",
    description: "AI-assisted manager action recommendations.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 6,
    requiredPlan: "commissioner",
  },
  {
    code: "commissioner_ai_full_draft_recap",
    category: "commissioner_function",
    featureLabel: "Full draft recap",
    description: "Full draft recap across league activity.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 6,
    requiredPlan: "commissioner",
  },
  {
    code: "commissioner_ai_full_league_recap",
    category: "commissioner_function",
    featureLabel: "Full league recap",
    description: "Cross-surface full league recap generation.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 7,
    requiredPlan: "commissioner",
  },
  {
    code: "commissioner_ai_large_analysis",
    category: "commissioner_function",
    featureLabel: "Large commissioner-wide analysis",
    description: "Large-scope commissioner-wide analysis run.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 9,
    requiredPlan: "commissioner",
  },

  // Backward-compatible in-use rules (mapped into matrix values)
  {
    code: "ai_chimmy_chat_message",
    category: "ai_feature",
    featureLabel: "Chimmy chat message",
    description: "Unified Chimmy chat response generation.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "ai_trade_eval_consensus",
    category: "ai_feature",
    featureLabel: "Trade analyzer full review (legacy)",
    description: "Legacy trade evaluator route mapped to full review pricing.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 3,
    requiredPlan: "pro",
  },
  {
    code: "ai_waiver_engine_run",
    category: "ai_feature",
    featureLabel: "One-off waiver suggestion (legacy)",
    description: "Legacy waiver route mapped to one-off waiver pricing.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "commissioner_ai_cycle_run",
    category: "commissioner_function",
    featureLabel: "Large commissioner-wide analysis (legacy cycle)",
    description: "Legacy AI Commissioner cycle endpoint mapped to large analysis pricing.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 9,
    requiredPlan: "commissioner",
  },
  {
    code: "commissioner_ai_chat_question",
    category: "commissioner_function",
    featureLabel: "AI Commissioner question",
    description: "Single AI Commissioner question and response.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "commissioner",
  },

  // Survivor — player AI (AF Pro) + host AI (AF Commissioner); costs are 1 / 2 / 3 tokens
  {
    code: "survivor_ai_vote_risk_quick",
    category: "ai_feature",
    featureLabel: "Survivor quick vote-risk check",
    description: "Fast vote exposure and swing-vote hint.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_idol_advice_simple",
    category: "ai_feature",
    featureLabel: "Survivor simple idol advice",
    description: "Short idol timing / play recommendation.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_minigame_one",
    category: "ai_feature",
    featureLabel: "Survivor one mini-game recommendation",
    description: "Single pick for an active mini-game.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_recap_short",
    category: "ai_feature",
    featureLabel: "Survivor short recap",
    description: "Brief weekly or tribal recap blurb.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_jury_sentiment_hint",
    category: "ai_feature",
    featureLabel: "Survivor juror sentiment hint",
    description: "Light jury perception cue (private to user).",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_confessional_polish",
    category: "ai_feature",
    featureLabel: "Survivor confessional polish",
    description: "Rewrite / tighten a confessional draft.",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_weekly_advice_pack",
    category: "ai_feature",
    featureLabel: "Survivor weekly advice package",
    description: "Bundled player strategy for the week.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_tribe_analysis_deep",
    category: "ai_feature",
    featureLabel: "Survivor deeper tribe analysis",
    description: "Tribe dynamics and numbers breakdown.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_challenge_strategy",
    category: "ai_feature",
    featureLabel: "Survivor challenge strategy breakdown",
    description: "Props, spreads, and lineup picks coaching.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_jury_management",
    category: "ai_feature",
    featureLabel: "Survivor jury management advice",
    description: "Finale and jury-facing narrative coaching.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_blindside_risk",
    category: "ai_feature",
    featureLabel: "Survivor blindside risk breakdown",
    description: "Who might flip and why.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_idol_timing",
    category: "ai_feature",
    featureLabel: "Survivor idol timing breakdown",
    description: "When to play advantages vs hold.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_alliance_threat_scan",
    category: "ai_feature",
    featureLabel: "Survivor alliance / threat scan",
    description: "Full-map alliance and threat read.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 3,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_episode_recap_full",
    category: "ai_feature",
    featureLabel: "Survivor full episode recap",
    description: "Long-form episode narrative recap.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 3,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_season_story_pack",
    category: "ai_feature",
    featureLabel: "Survivor season story package",
    description: "Season-long storyline and arc package.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 3,
    requiredPlan: "pro",
  },
  {
    code: "survivor_ai_host_vote_processing",
    category: "commissioner_function",
    featureLabel: "Survivor host vote processing assist",
    description: "Automation assist for tallying and validating votes.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "commissioner",
  },
  {
    code: "survivor_ai_host_idol_validation",
    category: "commissioner_function",
    featureLabel: "Survivor host idol validation assist",
    description: "Rules check for idol and advantage plays.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "commissioner",
  },
  {
    code: "survivor_ai_host_minigame_grade",
    category: "commissioner_function",
    featureLabel: "Survivor host mini-game grading assist",
    description: "Score mini-game submissions with explainable audit.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "commissioner",
  },
  {
    code: "survivor_ai_host_anti_collusion",
    category: "commissioner_function",
    featureLabel: "Survivor anti-collusion investigation",
    description: "Deep scan for coordinated voting or messaging patterns.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 3,
    requiredPlan: "commissioner",
  },
  {
    code: "survivor_ai_host_fairness_report",
    category: "commissioner_function",
    featureLabel: "Survivor commissioner fairness report",
    description: "League-wide fairness and competitive balance report.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 3,
    requiredPlan: "commissioner",
  },
  {
    code: "survivor_ai_host_weekly_recap",
    category: "commissioner_function",
    featureLabel: "Survivor weekly recap generator (host)",
    description: "Commissioner recap engine for story mode.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "commissioner",
  },
  {
    code: "survivor_ai_host_story_mode",
    category: "commissioner_function",
    featureLabel: "Survivor story mode control pack",
    description: "Tone, spoilers, and chapter breaks for season narrative.",
    tier: "high",
    complexity: "heavy",
    tokenCost: 3,
    requiredPlan: "commissioner",
  },
  {
    code: "big_brother_ai_vote_prediction",
    category: "ai_feature",
    featureLabel: "Big Brother quick insight / vote read",
    description: "Single-lens strategy or vote-dynamic read (1 token).",
    tier: "low",
    complexity: "simple",
    tokenCost: 1,
    requiredPlan: "pro",
  },
  {
    code: "big_brother_ai_alliance_read",
    category: "ai_feature",
    featureLabel: "Big Brother house / alliance analysis",
    description: "Deeper social and threat read (2 tokens).",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "pro",
  },
  {
    code: "big_brother_ai_strategy_report",
    category: "ai_feature",
    featureLabel: "Big Brother full weekly strategy report",
    description: "Full house breakdown and narrative recap (3 tokens).",
    tier: "high",
    complexity: "heavy",
    tokenCost: 3,
    requiredPlan: "pro",
  },
  {
    code: "big_brother_ai_host_challenge",
    category: "commissioner_function",
    featureLabel: "Big Brother HOH/Veto challenge narration",
    description: "Themed challenge copy for commissioner runs.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "commissioner",
  },
  {
    code: "big_brother_ai_host_ceremony",
    category: "commissioner_function",
    featureLabel: "Big Brother Chimmy host week",
    description: "Host narration and schedule framing.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "commissioner",
  },
  {
    code: "big_brother_ai_host_finale",
    category: "commissioner_function",
    featureLabel: "Big Brother finale moderator pack",
    description: "Finale tone and jury framing (no vote reveals).",
    tier: "high",
    complexity: "heavy",
    tokenCost: 3,
    requiredPlan: "commissioner",
  },
  {
    code: "big_brother_ai_host_fairness",
    category: "commissioner_function",
    featureLabel: "Big Brother fairness / anti-collusion scan",
    description: "Commissioner oversight narrative and checks.",
    tier: "mid",
    complexity: "moderate",
    tokenCost: 2,
    requiredPlan: "commissioner",
  },
] as const

const MATRIX_BY_CODE = new Map<string, TokenPricingMatrixEntry>(
  TOKEN_SPEND_RULE_MATRIX.map((entry) => [entry.code, entry])
)

export function getTokenSpendRuleMatrixEntry(code: string): TokenPricingMatrixEntry | null {
  return MATRIX_BY_CODE.get(code) ?? null
}

export function listTokenSpendRuleMatrix(): TokenPricingMatrixEntry[] {
  return TOKEN_SPEND_RULE_MATRIX.map((entry) => ({ ...entry }))
}
