/**
 * Decision OS — Phase 5.6 Intelligence API Internal Resolvers.
 *
 * Pure bridge functions that map internal behavioral intelligence types to the
 * curated external API contracts defined in `api/contracts.ts`.
 *
 * These resolvers are the single authoritative enforcement point for all
 * privacy stripping rules. Every excluded field is annotated with a STRIPS comment.
 *
 * Architecture constraints (ADR_F5_6_INTELLIGENCE_API_RESOLVERS.md):
 *   - Pure functions: no IO, no DB access, no auth, no network calls
 *   - No input mutation
 *   - No internal Decision OS fields in output (warnings, derivedFrom, provenance, etc.)
 *   - managerId / leagueId echoed as-is (caller's own tenant-scoped IDs)
 *
 * Usage (future Phase 5.7 route handler):
 *   const data = resolveManagerIntelligence(intel, requestId, 'manager')
 *   return NextResponse.json(data)
 */

import type { ManagerBehavioralIntelligence, ManagerNudge } from '../manager-intelligence'
import type {
  LeagueBehavioralIntelligence,
  LeagueActivityDimension,
  LeagueCommissionerRecommendation,
} from '../league-intelligence'
import type {
  PlatformBehavioralIntelligence,
  PlatformEcosystemDimension,
  HeatmapCell,
  PlatformInterventionOpportunity,
} from '../platform-intelligence'
import type {
  IntelligenceApiResponse,
  IntelligenceApiMeta,
  IntelligenceTier,
  ManagerIntelligenceV1,
  ManagerEngagementDimensionsV1,
  ManagerNudgeV1,
  LeagueIntelligenceV1,
  LeagueActivityDimensionV1,
  LeagueRecommendationV1,
  PlatformIntelligenceBasicV1,
  PlatformIntelligenceV1,
  PlatformEcosystemDimensionV1,
  PlatformHeatmapCellV1,
  PlatformInterventionV1,
} from './contracts'

// ── Envelope builder ──────────────────────────────────────────────────────────

function buildMeta(
  derivedAt: string,
  completeness: number,
  tier: IntelligenceTier,
  requestId: string,
): IntelligenceApiMeta {
  return { requestId, derivedAt, completeness, version: 'v1', tier }
}

// ─────────────────────────────────────────────────────────────────────────────
// Manager Intelligence resolver
// ─────────────────────────────────────────────────────────────────────────────

function mapManagerNudge(nudge: ManagerNudge): ManagerNudgeV1 {
  // STRIPS: signal (internal machine-readable trigger key)
  // STRIPS: supportingEventIds (internal event reference list)
  return {
    nudgeId:  nudge.nudgeId,
    priority: nudge.priority,
    category: nudge.category,
    message:  nudge.message,
  }
}

function mapEngagementDimensions(
  intel: ManagerBehavioralIntelligence,
): ManagerEngagementDimensionsV1 {
  // STRIPS (per dimension): eventCount, lastEventAt, warnings
  return {
    lineup: { score: intel.lineupEngagement.score, level: intel.lineupEngagement.level },
    waiver: { score: intel.waiverEngagement.score, level: intel.waiverEngagement.level },
    trade:  { score: intel.tradeEngagement.score,  level: intel.tradeEngagement.level  },
    draft:  { score: intel.draftEngagement.score,  level: intel.draftEngagement.level  },
  }
}

/**
 * Maps `ManagerBehavioralIntelligence` to the external `ManagerIntelligenceV1` contract.
 *
 * Enforces all privacy stripping rules for the manager intelligence endpoint:
 *   - Nudges lose `signal` and `supportingEventIds`
 *   - Engagement dimensions lose `eventCount`, `lastEventAt`, `warnings`
 *   - `inactivityWarning`, `derivedFrom`, `lookbackDays`, `warnings` are excluded
 *
 * @param intel   Internal manager intelligence object (not mutated)
 * @param requestId  UUID generated by the route handler for tracing
 * @param tier    Caller's effective tier (usually 'manager'; recorded in meta)
 */
export function resolveManagerIntelligence(
  intel: ManagerBehavioralIntelligence,
  requestId: string,
  tier: IntelligenceTier,
): IntelligenceApiResponse<ManagerIntelligenceV1> {
  // STRIPS: inactivityWarning, derivedFrom, lookbackDays, warnings
  const data: ManagerIntelligenceV1 = {
    managerId:              intel.managerId,
    leagueId:               intel.leagueId,
    participationTier:      intel.participationTier,
    retentionRisk:          intel.retentionRisk,
    retentionRiskReasons:   [...intel.retentionRiskReasons],
    overallEngagementScore: intel.overallEngagementScore,
    engagementDimensions:   mapEngagementDimensions(intel),
    daysSinceLastActivity:  intel.daysSinceLastActivity,
    isInactive:             intel.isInactive,
    nudges:                 intel.nudges.map(mapManagerNudge),
    completeness:           intel.completeness,
    derivedAt:              intel.derivedAt,
  }
  return { data, meta: buildMeta(intel.derivedAt, intel.completeness, tier, requestId) }
}

// ─────────────────────────────────────────────────────────────────────────────
// League Intelligence resolver
// ─────────────────────────────────────────────────────────────────────────────

function mapActivityDimension(dim: LeagueActivityDimension): LeagueActivityDimensionV1 {
  // STRIPS: count (raw event total), warnings
  return {
    tier:           dim.tier,
    perManagerRate: dim.perManagerRate,
  }
}

function mapLeagueRecommendation(
  rec: LeagueCommissionerRecommendation,
): LeagueRecommendationV1 {
  // STRIPS: signal (internal machine-readable trigger key)
  return {
    recommendationId: rec.recommendationId,
    priority:         rec.priority,
    category:         rec.category,
    message:          rec.message,
  }
}

/**
 * Maps `LeagueBehavioralIntelligence` to the external `LeagueIntelligenceV1` contract.
 *
 * Enforces all privacy stripping rules for the league intelligence endpoint:
 *   - Activity dimensions lose `count` and `warnings`
 *   - Recommendations lose `signal`
 *   - `retentionRiskReasons`, `commissionerWorkloadItems`, `healthNarrativeInputs`,
 *     `inactiveManagerCount`, `derivedFrom`, `managerCount`, `lookbackDays`,
 *     `warnings` are excluded
 *
 * @param intel   Internal league intelligence object (not mutated)
 * @param requestId  UUID generated by the route handler for tracing
 * @param tier    Caller's effective tier (usually 'commissioner'; recorded in meta)
 */
export function resolveLeagueIntelligence(
  intel: LeagueBehavioralIntelligence,
  requestId: string,
  tier: IntelligenceTier,
): IntelligenceApiResponse<LeagueIntelligenceV1> {
  // STRIPS: retentionRiskReasons, commissionerWorkloadItems, healthNarrativeInputs,
  //         inactiveManagerCount, derivedFrom, managerCount, lookbackDays, warnings
  const data: LeagueIntelligenceV1 = {
    leagueId:               intel.leagueId,
    leagueEngagementScore:  intel.leagueEngagementScore,
    leagueEngagementTier:   intel.leagueEngagementTier,
    participationDistribution: { ...intel.participationDistribution },
    tradeActivity:          mapActivityDimension(intel.tradeActivity),
    waiverActivity:         mapActivityDimension(intel.waiverActivity),
    draftActivity:          mapActivityDimension(intel.draftActivity),
    retentionRisk:          intel.retentionRisk,
    commissionerWorkload:   intel.commissionerWorkload,
    recommendations:        intel.recommendations.map(mapLeagueRecommendation),
    completeness:           intel.completeness,
    derivedAt:              intel.derivedAt,
  }
  return { data, meta: buildMeta(intel.derivedAt, intel.completeness, tier, requestId) }
}

// ─────────────────────────────────────────────────────────────────────────────
// Platform Intelligence — Basic tier resolver
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Maps `PlatformBehavioralIntelligence` to the aggregate-only `PlatformIntelligenceBasicV1`.
 *
 * The basic tier is intentionally minimal — safe for browser embedding and
 * public dashboards because it contains no per-league or per-manager identifiers
 * and no absolute counts that reveal platform scale.
 *
 * Included: engagement score/tier, league health percentages (only), momentum
 *   signal, trend confidence, completeness, derivedAt.
 * Everything else is excluded.
 *
 * @param intel   Internal platform intelligence object (not mutated)
 * @param requestId  UUID generated by the route handler for tracing
 */
export function resolvePlatformIntelligenceBasic(
  intel: PlatformBehavioralIntelligence,
  requestId: string,
): IntelligenceApiResponse<PlatformIntelligenceBasicV1> {
  // STRIPS: leagueHealthDistribution absolute counts, commissionerQualityDistribution,
  //         retentionDistribution, tradeEcosystem, waiverEcosystem, draftParticipation
  //         (all rates), engagementTrends counts/ratios, activityHeatmap,
  //         interventionOpportunities, uncertainty, warnings, provenance
  const data: PlatformIntelligenceBasicV1 = {
    platformEngagementScore: intel.platformEngagementScore,
    platformEngagementTier:  intel.platformEngagementTier,
    leagueHealthSummary: {
      healthyPercent: intel.leagueHealthDistribution.healthyPercent,
      atRiskPercent:  intel.leagueHealthDistribution.atRiskPercent,
    },
    momentumSignal:  intel.engagementTrends.momentumSignal,
    trendConfidence: intel.engagementTrends.trendConfidence,
    completeness:    intel.completeness,
    derivedAt:       intel.derivedAt,
  }
  return { data, meta: buildMeta(intel.derivedAt, intel.completeness, 'basic', requestId) }
}

// ─────────────────────────────────────────────────────────────────────────────
// Platform Intelligence — Full tier resolver
// ─────────────────────────────────────────────────────────────────────────────

function mapPlatformEcosystemDimension(
  dim: PlatformEcosystemDimension,
): PlatformEcosystemDimensionV1 {
  // STRIPS: totalEvents, activeLeagues, totalLeagues, warnings
  return {
    tier:                dim.tier,
    activeLeaguePercent: dim.activeLeaguePercent,
    perLeagueRate:       dim.perLeagueRate,
    perManagerRate:      dim.perManagerRate,
  }
}

function mapHeatmapCell(cell: HeatmapCell): PlatformHeatmapCellV1 {
  return { dayOfWeek: cell.dayOfWeek, hour: cell.hour, count: cell.count }
}

function mapIntervention(opp: PlatformInterventionOpportunity): PlatformInterventionV1 {
  // signal IS included in external API — machine-readable for operator-side routing
  // managerId IS included — it is the caller's own tenant-scoped identifier
  const result: PlatformInterventionV1 = {
    opportunityId: opp.opportunityId,
    scope:         opp.scope,
    priority:      opp.priority,
    leagueId:      opp.leagueId,
    signal:        opp.signal,
    message:       opp.message,
  }
  if (opp.managerId !== undefined) result.managerId = opp.managerId
  return result
}

/**
 * Maps `PlatformBehavioralIntelligence` to the full `PlatformIntelligenceV1` contract.
 *
 * Includes all platform-scope signals. Enforces stripping of internal fields:
 *   - Ecosystem dimensions lose `totalEvents`, `activeLeagues`, `totalLeagues`, `warnings`
 *   - `engagementTrends.warnings` excluded
 *   - `activityHeatmap.warnings` excluded
 *   - Top-level `warnings` excluded
 *   - `provenance` (internal data-pipeline metadata) excluded
 *
 * @param intel   Internal platform intelligence object (not mutated)
 * @param requestId  UUID generated by the route handler for tracing
 */
export function resolvePlatformIntelligenceFull(
  intel: PlatformBehavioralIntelligence,
  requestId: string,
): IntelligenceApiResponse<PlatformIntelligenceV1> {
  // STRIPS: top-level warnings, provenance
  const data: PlatformIntelligenceV1 = {
    platformEngagementScore: intel.platformEngagementScore,
    platformEngagementTier:  intel.platformEngagementTier,
    uncertainty:             intel.uncertainty,

    leagueHealthDistribution: {
      elite:          intel.leagueHealthDistribution.elite,
      active:         intel.leagueHealthDistribution.active,
      moderate:       intel.leagueHealthDistribution.moderate,
      passive:        intel.leagueHealthDistribution.passive,
      dormant:        intel.leagueHealthDistribution.dormant,
      totalLeagues:   intel.leagueHealthDistribution.totalLeagues,
      healthyPercent: intel.leagueHealthDistribution.healthyPercent,
      atRiskPercent:  intel.leagueHealthDistribution.atRiskPercent,
    },

    commissionerQualityDistribution: {
      light:             intel.commissionerQualityDistribution.light,
      moderate:          intel.commissionerQualityDistribution.moderate,
      heavy:             intel.commissionerQualityDistribution.heavy,
      critical:          intel.commissionerQualityDistribution.critical,
      totalLeagues:      intel.commissionerQualityDistribution.totalLeagues,
      managedPercent:    intel.commissionerQualityDistribution.managedPercent,
      overloadedPercent: intel.commissionerQualityDistribution.overloadedPercent,
    },

    retentionDistribution: {
      managersByCriticalRisk:     intel.retentionDistribution.managersByCriticalRisk,
      managersByHighRisk:         intel.retentionDistribution.managersByHighRisk,
      managersByMediumRisk:       intel.retentionDistribution.managersByMediumRisk,
      managersByLowRisk:          intel.retentionDistribution.managersByLowRisk,
      totalManagers:              intel.retentionDistribution.totalManagers,
      managerCriticalRiskPercent: intel.retentionDistribution.managerCriticalRiskPercent,
      managerAtRiskPercent:       intel.retentionDistribution.managerAtRiskPercent,
      leaguesByCriticalRisk:      intel.retentionDistribution.leaguesByCriticalRisk,
      leaguesByHighRisk:          intel.retentionDistribution.leaguesByHighRisk,
      leaguesByMediumRisk:        intel.retentionDistribution.leaguesByMediumRisk,
      leaguesByLowRisk:           intel.retentionDistribution.leaguesByLowRisk,
      totalLeagues:               intel.retentionDistribution.totalLeagues,
      leagueCriticalRiskPercent:  intel.retentionDistribution.leagueCriticalRiskPercent,
      leagueAtRiskPercent:        intel.retentionDistribution.leagueAtRiskPercent,
    },

    // STRIPS per ecosystem: totalEvents, activeLeagues, totalLeagues, warnings
    tradeEcosystem:    mapPlatformEcosystemDimension(intel.tradeEcosystem),
    waiverEcosystem:   mapPlatformEcosystemDimension(intel.waiverEcosystem),
    draftParticipation: mapPlatformEcosystemDimension(intel.draftParticipation),

    engagementTrends: {
      // STRIPS: warnings
      sevenDayEventCount:           intel.engagementTrends.sevenDayEventCount,
      thirtyDayEventCount:          intel.engagementTrends.thirtyDayEventCount,
      recentActivityRatio:          intel.engagementTrends.recentActivityRatio,
      recentlyActiveManagerPercent: intel.engagementTrends.recentlyActiveManagerPercent,
      momentumSignal:               intel.engagementTrends.momentumSignal,
      trendConfidence:              intel.engagementTrends.trendConfidence,
    },

    activityHeatmap: {
      // STRIPS: warnings
      cells:               intel.activityHeatmap.cells.map(mapHeatmapCell),
      peakCellKey:         intel.activityHeatmap.peakCellKey,
      peakDayOfWeek:       intel.activityHeatmap.peakDayOfWeek,
      peakHour:            intel.activityHeatmap.peakHour,
      peakCount:           intel.activityHeatmap.peakCount,
      totalEventsAnalyzed: intel.activityHeatmap.totalEventsAnalyzed,
    },

    interventionOpportunities: intel.interventionOpportunities.map(mapIntervention),

    completeness: intel.completeness,
    derivedAt:    intel.derivedAt,
  }
  return { data, meta: buildMeta(intel.derivedAt, intel.completeness, 'platform', requestId) }
}
