"use client"
import Image from "next/image"
import { Check, Lock, Radio, Trophy } from "lucide-react"
import type { WorldCupMatchView, WorldCupPickView } from "@/lib/world-cup/types"
function Logo({ src, name }: { src?: string | null; name: string }) { return src ? <Image src={src} alt="" width={28} height={28} className="h-7 w-7 shrink-0 rounded-full bg-white object-contain p-0.5" /> : <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-white/10 text-[10px] font-black text-white/70">{name.slice(0, 2).toUpperCase()}</span> }
export default function WorldCupMatchupCard({ match, pick, locked, onPick }: { match: WorldCupMatchView; pick?: WorldCupPickView; locked?: boolean; onPick?: (match: WorldCupMatchView, side: "home" | "away") => void }) {
  const teams = [{ side: "home" as const, slotKey: match.homeSlotKey, teamId: match.homeTeamId, name: match.homeTeamName, logo: match.homeTeamLogo, score: match.homeScore }, { side: "away" as const, slotKey: match.awaySlotKey, teamId: match.awayTeamId, name: match.awayTeamName, logo: match.awayTeamLogo, score: match.awayScore }]
  return <article className="w-72 shrink-0 rounded-lg border border-white/10 bg-zinc-950/80 p-3 shadow-2xl shadow-black/30"><div className="mb-2 flex items-center justify-between gap-2"><span className="text-[10px] font-black uppercase tracking-[0.18em] text-white/35">Match {match.matchNumber}</span><div className="flex items-center gap-1">{match.status === "live" || match.status === "halftime" ? <span className="inline-flex items-center gap-1 rounded-full bg-rose-500/15 px-2 py-0.5 text-[10px] font-bold text-rose-200"><Radio className="h-3 w-3" />Live</span> : null}{match.status === "final" ? <span className="rounded-full bg-emerald-500/15 px-2 py-0.5 text-[10px] font-bold text-emerald-200">Final</span> : null}{locked ? <Lock className="h-3.5 w-3.5 text-white/35" /> : null}</div></div><div className="space-y-2">{teams.map((t) => { const selected = pick?.selectedSlotKey === t.slotKey || Boolean(pick?.selectedTeamId && t.teamId && pick.selectedTeamId === t.teamId); const winner = match.status === "final" && (match.winnerTeamName === t.name || Boolean(match.winnerTeamId && t.teamId === match.winnerTeamId)); return <button key={t.side} type="button" disabled={locked} onClick={() => onPick?.(match, t.side)} className={`flex h-14 w-full items-center gap-2 rounded-md border px-2 text-left transition ${selected ? "border-cyan-300/70 bg-cyan-300/10" : "border-white/10 bg-white/[0.03]"} ${winner ? "border-emerald-300/70 bg-emerald-400/10" : ""} ${match.status === "final" && selected && !winner ? "opacity-45 line-through" : ""}`}><Logo src={t.logo} name={t.name} /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold text-white">{t.name}</span><span className="block truncate text-[10px] text-white/35">{t.slotKey}</span></span>{t.score != null ? <span className="text-sm font-black text-white">{t.score}</span> : null}{selected ? <Check className="h-4 w-4 text-cyan-200" /> : null}{winner ? <Trophy className="h-4 w-4 text-emerald-200" /> : null}</button> })}</div></article>
}
