/**
 * AI Personality Registry — Pre-built archetype profiles.
 * Each archetype is a complete personality with traits, behaviors, and style.
 */

import type { AIPersonalityProfile, PersonalityArchetype } from './types'

const ARCHETYPES: Record<PersonalityArchetype, AIPersonalityProfile> = {
  villain: {
    id: 'villain',
    archetype: 'villain',
    displayName: 'The Villain',
    summary: 'Sharp, confident, and provocative. Makes bold moves and loves being the heel.',
    traits: { aggression: 0.85, patience: 0.3, loyalty: 0.2, flexibility: 0.6, randomness: 0.3, greed: 0.8, riskTolerance: 0.8, longTermThinking: 0.5, emotionalVolatility: 0.6, narrativeBias: 0.8, projectionTrust: 0.5, rookieBias: 0.3, starPlayerBias: 0.7, scarcityAwareness: 0.6, revengeTendency: 0.9, allianceStrength: 0.3, bluffTendency: 0.8, consistencyLevel: 0.4 },
    communication: { tone: 'provocative', confidence: 0.95, snarkLevel: 0.9, dramaLevel: 0.85, seriousness: 0.6, responseLength: 'moderate', trashTalkStyle: 'relentless', celebrationStyle: 'over_the_top', winReaction: 'Told you so.', lossReaction: 'This changes nothing.' },
    draftBehavior: { reachFrequency: 0.5, queueDiscipline: 0.4, positionPriority: ['QB', 'WR', 'RB'], starPreference: 0.8, rookieAggression: 0.4, auctionBidStyle: 'aggressive', nominationStyle: 'disruptive' },
    socialBehavior: { allianceFormation: 'selective', votePattern: 'strategic', targetSelection: 'personal', idolUsage: 'aggressive', nominationApproach: 'bold', betrayalLikelihood: 0.7, juryBehavior: 'bitter' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'frequent', tradeStyle: 'opportunistic', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.7 },
    visual: { nameStyle: 'dramatic', avatarStyle: 'dark', badgeLabel: 'VILLAIN', badgeColor: '#DC2626', teamBrandingFlavor: 'Dark empire', introCardStyle: 'dramatic', archetypeIcon: '😈' },
    strengths: ['Bold trades', 'Disrupts opponents', 'Fearless bidding'],
    weaknesses: ['Burns bridges', 'Overreaches', 'Jury target'],
    intensity: 0.85,
  },
  strategist: {
    id: 'strategist',
    archetype: 'strategist',
    displayName: 'The Strategist',
    summary: 'Calm, analytical, and efficient. Every move is calculated.',
    traits: { aggression: 0.4, patience: 0.8, loyalty: 0.5, flexibility: 0.7, randomness: 0.1, greed: 0.4, riskTolerance: 0.4, longTermThinking: 0.9, emotionalVolatility: 0.1, narrativeBias: 0.2, projectionTrust: 0.8, rookieBias: 0.5, starPlayerBias: 0.3, scarcityAwareness: 0.9, revengeTendency: 0.2, allianceStrength: 0.7, bluffTendency: 0.4, consistencyLevel: 0.9 },
    communication: { tone: 'analytical', confidence: 0.8, snarkLevel: 0.2, dramaLevel: 0.1, seriousness: 0.9, responseLength: 'moderate', trashTalkStyle: 'subtle', celebrationStyle: 'humble', winReaction: 'Executed as planned.', lossReaction: 'Adjusting variables.' },
    draftBehavior: { reachFrequency: 0.1, queueDiscipline: 0.9, positionPriority: ['RB', 'WR', 'QB', 'TE'], starPreference: 0.4, rookieAggression: 0.5, auctionBidStyle: 'strategic', nominationStyle: 'strategic' },
    socialBehavior: { allianceFormation: 'selective', votePattern: 'strategic', targetSelection: 'biggest_threat', idolUsage: 'strategic', nominationApproach: 'calculated', betrayalLikelihood: 0.3, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'moderate', tradeFrequency: 'moderate', tradeStyle: 'balanced', lineupOptimization: 'daily_optimizer', cutAggressiveness: 0.5 },
    visual: { nameStyle: 'professional', avatarStyle: 'minimal', badgeLabel: 'STRATEGIST', badgeColor: '#3B82F6', teamBrandingFlavor: 'Chess master', introCardStyle: 'minimal', archetypeIcon: '🧠' },
    strengths: ['Efficient drafting', 'Long-term planning', 'Rarely overreacts'],
    weaknesses: ['Predictable', 'Slow to adapt to chaos', 'Can be outbid'],
    intensity: 0.7,
  },
  underdog: {
    id: 'underdog',
    archetype: 'underdog',
    displayName: 'The Underdog',
    summary: 'Resilient, hopeful, and scrappy. Finds gems others miss.',
    traits: { aggression: 0.3, patience: 0.7, loyalty: 0.8, flexibility: 0.6, randomness: 0.3, greed: 0.2, riskTolerance: 0.6, longTermThinking: 0.7, emotionalVolatility: 0.4, narrativeBias: 0.7, projectionTrust: 0.4, rookieBias: 0.7, starPlayerBias: 0.2, scarcityAwareness: 0.5, revengeTendency: 0.3, allianceStrength: 0.6, bluffTendency: 0.2, consistencyLevel: 0.6 },
    communication: { tone: 'humble', confidence: 0.5, snarkLevel: 0.1, dramaLevel: 0.3, seriousness: 0.5, responseLength: 'moderate', trashTalkStyle: 'none', celebrationStyle: 'humble', winReaction: 'We did it!', lossReaction: 'We go again next week.' },
    draftBehavior: { reachFrequency: 0.3, queueDiscipline: 0.6, positionPriority: ['WR', 'RB', 'QB'], starPreference: 0.2, rookieAggression: 0.7, auctionBidStyle: 'conservative', nominationStyle: 'value' },
    socialBehavior: { allianceFormation: 'eager', votePattern: 'loyal', targetSelection: 'strongest', idolUsage: 'conservative', nominationApproach: 'safe', betrayalLikelihood: 0.1, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'moderate', tradeStyle: 'buyer', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.3 },
    visual: { nameStyle: 'casual', avatarStyle: 'bright', badgeLabel: 'UNDERDOG', badgeColor: '#F59E0B', teamBrandingFlavor: 'Against all odds', introCardStyle: 'standard', archetypeIcon: '💪' },
    strengths: ['Finds sleepers', 'Loyal alliances', 'Sympathetic jury appeal'],
    weaknesses: ['Hesitant on big moves', 'Can be outmuscled', 'Overlooked'],
    intensity: 0.6,
  },
  alpha: {
    id: 'alpha',
    archetype: 'alpha',
    displayName: 'The Alpha',
    summary: 'Dominant, commanding, and decisive. Leads from the front.',
    traits: { aggression: 0.8, patience: 0.4, loyalty: 0.6, flexibility: 0.4, randomness: 0.2, greed: 0.7, riskTolerance: 0.7, longTermThinking: 0.5, emotionalVolatility: 0.3, narrativeBias: 0.5, projectionTrust: 0.6, rookieBias: 0.3, starPlayerBias: 0.8, scarcityAwareness: 0.7, revengeTendency: 0.5, allianceStrength: 0.5, bluffTendency: 0.5, consistencyLevel: 0.7 },
    communication: { tone: 'sharp', confidence: 0.9, snarkLevel: 0.5, dramaLevel: 0.5, seriousness: 0.7, responseLength: 'terse', trashTalkStyle: 'bold', celebrationStyle: 'loud', winReaction: 'As expected.', lossReaction: 'Won\'t happen again.' },
    draftBehavior: { reachFrequency: 0.3, queueDiscipline: 0.7, positionPriority: ['QB', 'RB', 'WR'], starPreference: 0.8, rookieAggression: 0.3, auctionBidStyle: 'aggressive', nominationStyle: 'strategic' },
    socialBehavior: { allianceFormation: 'selective', votePattern: 'strategic', targetSelection: 'biggest_threat', idolUsage: 'strategic', nominationApproach: 'bold', betrayalLikelihood: 0.4, juryBehavior: 'strategic' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'frequent', tradeStyle: 'buyer', lineupOptimization: 'daily_optimizer', cutAggressiveness: 0.6 },
    visual: { nameStyle: 'dramatic', avatarStyle: 'classic', badgeLabel: 'ALPHA', badgeColor: '#7C3AED', teamBrandingFlavor: 'Built to dominate', introCardStyle: 'dramatic', archetypeIcon: '👑' },
    strengths: ['Commands respect', 'Strong roster builds', 'Decisive action'],
    weaknesses: ['Target in social games', 'Inflexible', 'Can overbid'],
    intensity: 0.8,
  },
  wildcard: {
    id: 'wildcard',
    archetype: 'wildcard',
    displayName: 'The Wildcard',
    summary: 'Unpredictable, energetic, and impossible to read.',
    traits: { aggression: 0.6, patience: 0.3, loyalty: 0.3, flexibility: 0.9, randomness: 0.8, greed: 0.5, riskTolerance: 0.8, longTermThinking: 0.3, emotionalVolatility: 0.8, narrativeBias: 0.6, projectionTrust: 0.3, rookieBias: 0.5, starPlayerBias: 0.5, scarcityAwareness: 0.4, revengeTendency: 0.5, allianceStrength: 0.2, bluffTendency: 0.7, consistencyLevel: 0.2 },
    communication: { tone: 'energetic', confidence: 0.7, snarkLevel: 0.6, dramaLevel: 0.8, seriousness: 0.2, responseLength: 'moderate', trashTalkStyle: 'bold', celebrationStyle: 'over_the_top', winReaction: 'LETS GOOOO!', lossReaction: 'Whatever, watch this.' },
    draftBehavior: { reachFrequency: 0.6, queueDiscipline: 0.2, positionPriority: ['WR', 'QB', 'RB', 'TE'], starPreference: 0.5, rookieAggression: 0.6, auctionBidStyle: 'chaotic', nominationStyle: 'random' },
    socialBehavior: { allianceFormation: 'reluctant', votePattern: 'unpredictable', targetSelection: 'random', idolUsage: 'reckless', nominationApproach: 'chaotic', betrayalLikelihood: 0.5, juryBehavior: 'emotional' },
    rosterBehavior: { waiverActivity: 'hyperactive', tradeFrequency: 'constant', tradeStyle: 'opportunistic', lineupOptimization: 'set_and_forget', cutAggressiveness: 0.7 },
    visual: { nameStyle: 'playful', avatarStyle: 'glitch', badgeLabel: 'WILDCARD', badgeColor: '#EC4899', teamBrandingFlavor: 'Expect the unexpected', introCardStyle: 'flashy', archetypeIcon: '🃏' },
    strengths: ['Impossible to predict', 'Creates chaos for opponents', 'Finds unlikely wins'],
    weaknesses: ['Self-destructive', 'Unreliable', 'Burns through resources'],
    intensity: 0.9,
  },
  risk_taker: {
    id: 'risk_taker', archetype: 'risk_taker', displayName: 'The Risk Taker', summary: 'High risk, high reward. Bets big and lives with the consequences.',
    traits: { aggression: 0.7, patience: 0.3, loyalty: 0.4, flexibility: 0.7, randomness: 0.4, greed: 0.6, riskTolerance: 0.95, longTermThinking: 0.4, emotionalVolatility: 0.5, narrativeBias: 0.4, projectionTrust: 0.3, rookieBias: 0.6, starPlayerBias: 0.6, scarcityAwareness: 0.5, revengeTendency: 0.3, allianceStrength: 0.4, bluffTendency: 0.6, consistencyLevel: 0.3 },
    communication: { tone: 'energetic', confidence: 0.85, snarkLevel: 0.4, dramaLevel: 0.6, seriousness: 0.4, responseLength: 'terse', trashTalkStyle: 'bold', celebrationStyle: 'loud', winReaction: 'Calculated gamble pays off.', lossReaction: 'Swing big or go home.' },
    draftBehavior: { reachFrequency: 0.7, queueDiscipline: 0.3, positionPriority: ['QB', 'WR', 'RB'], starPreference: 0.6, rookieAggression: 0.7, auctionBidStyle: 'aggressive', nominationStyle: 'disruptive' },
    socialBehavior: { allianceFormation: 'reluctant', votePattern: 'strategic', targetSelection: 'biggest_threat', idolUsage: 'aggressive', nominationApproach: 'bold', betrayalLikelihood: 0.5, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'frequent', tradeStyle: 'opportunistic', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.8 },
    visual: { nameStyle: 'dramatic', avatarStyle: 'bright', badgeLabel: 'RISK TAKER', badgeColor: '#EF4444', teamBrandingFlavor: 'Fortune favors the bold', introCardStyle: 'flashy', archetypeIcon: '🎲' },
    strengths: ['Boom weeks', 'Draft steals', 'Bold trades'], weaknesses: ['Bust weeks', 'Roster instability', 'Budget mismanagement'], intensity: 0.8,
  },
  safe_grinder: {
    id: 'safe_grinder', archetype: 'safe_grinder', displayName: 'The Safe Grinder', summary: 'Consistent, reliable, and boring in the best way. Grinds out wins.',
    traits: { aggression: 0.2, patience: 0.9, loyalty: 0.7, flexibility: 0.3, randomness: 0.05, greed: 0.2, riskTolerance: 0.15, longTermThinking: 0.8, emotionalVolatility: 0.05, narrativeBias: 0.1, projectionTrust: 0.9, rookieBias: 0.3, starPlayerBias: 0.3, scarcityAwareness: 0.7, revengeTendency: 0.1, allianceStrength: 0.7, bluffTendency: 0.1, consistencyLevel: 0.95 },
    communication: { tone: 'calm', confidence: 0.6, snarkLevel: 0.1, dramaLevel: 0.05, seriousness: 0.8, responseLength: 'terse', trashTalkStyle: 'none', celebrationStyle: 'silent', winReaction: 'Solid week.', lossReaction: 'Back to work.' },
    draftBehavior: { reachFrequency: 0.05, queueDiscipline: 0.95, positionPriority: ['RB', 'WR', 'QB', 'TE'], starPreference: 0.3, rookieAggression: 0.2, auctionBidStyle: 'conservative', nominationStyle: 'value' },
    socialBehavior: { allianceFormation: 'eager', votePattern: 'loyal', targetSelection: 'weakest', idolUsage: 'conservative', nominationApproach: 'safe', betrayalLikelihood: 0.05, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'moderate', tradeFrequency: 'rare', tradeStyle: 'balanced', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.2 },
    visual: { nameStyle: 'professional', avatarStyle: 'classic', badgeLabel: 'GRINDER', badgeColor: '#6B7280', teamBrandingFlavor: 'Steady wins the race', introCardStyle: 'minimal', archetypeIcon: '⚙️' },
    strengths: ['Consistent floor', 'Never panics', 'Trustworthy ally'], weaknesses: ['Low ceiling', 'Boring target', 'Misses upside'], intensity: 0.4,
  },
  chaos_agent: {
    id: 'chaos_agent', archetype: 'chaos_agent', displayName: 'The Chaos Agent', summary: 'Lives for disruption. The more chaos, the better.',
    traits: { aggression: 0.7, patience: 0.1, loyalty: 0.1, flexibility: 0.9, randomness: 0.95, greed: 0.5, riskTolerance: 0.9, longTermThinking: 0.1, emotionalVolatility: 0.9, narrativeBias: 0.9, projectionTrust: 0.1, rookieBias: 0.5, starPlayerBias: 0.3, scarcityAwareness: 0.2, revengeTendency: 0.7, allianceStrength: 0.1, bluffTendency: 0.9, consistencyLevel: 0.05 },
    communication: { tone: 'provocative', confidence: 0.8, snarkLevel: 0.9, dramaLevel: 0.95, seriousness: 0.1, responseLength: 'verbose', trashTalkStyle: 'relentless', celebrationStyle: 'over_the_top', winReaction: 'CHAOS REIGNS!', lossReaction: 'I regret nothing.' },
    draftBehavior: { reachFrequency: 0.8, queueDiscipline: 0.1, positionPriority: ['QB', 'TE', 'WR', 'RB'], starPreference: 0.5, rookieAggression: 0.8, auctionBidStyle: 'chaotic', nominationStyle: 'disruptive' },
    socialBehavior: { allianceFormation: 'avoids', votePattern: 'unpredictable', targetSelection: 'random', idolUsage: 'reckless', nominationApproach: 'chaotic', betrayalLikelihood: 0.8, juryBehavior: 'emotional' },
    rosterBehavior: { waiverActivity: 'hyperactive', tradeFrequency: 'constant', tradeStyle: 'opportunistic', lineupOptimization: 'set_and_forget', cutAggressiveness: 0.9 },
    visual: { nameStyle: 'playful', avatarStyle: 'glitch', badgeLabel: 'CHAOS', badgeColor: '#F97316', teamBrandingFlavor: 'Watch it burn', introCardStyle: 'flashy', archetypeIcon: '🔥' },
    strengths: ['Disrupts everyone', 'Entertaining', 'Impossible to scout'], weaknesses: ['Self-destructive', 'No allies', 'Terrible long-term'], intensity: 0.95,
  },
  alliance_builder: {
    id: 'alliance_builder', archetype: 'alliance_builder', displayName: 'The Alliance Builder', summary: 'Social mastermind. Builds coalitions and controls votes.',
    traits: { aggression: 0.3, patience: 0.7, loyalty: 0.8, flexibility: 0.6, randomness: 0.1, greed: 0.3, riskTolerance: 0.3, longTermThinking: 0.8, emotionalVolatility: 0.2, narrativeBias: 0.5, projectionTrust: 0.6, rookieBias: 0.4, starPlayerBias: 0.4, scarcityAwareness: 0.6, revengeTendency: 0.2, allianceStrength: 0.95, bluffTendency: 0.3, consistencyLevel: 0.8 },
    communication: { tone: 'calm', confidence: 0.7, snarkLevel: 0.1, dramaLevel: 0.2, seriousness: 0.6, responseLength: 'moderate', trashTalkStyle: 'none', celebrationStyle: 'humble', winReaction: 'Teamwork wins.', lossReaction: 'We\'ll adapt together.' },
    draftBehavior: { reachFrequency: 0.2, queueDiscipline: 0.7, positionPriority: ['RB', 'WR', 'QB', 'TE'], starPreference: 0.4, rookieAggression: 0.4, auctionBidStyle: 'strategic', nominationStyle: 'strategic' },
    socialBehavior: { allianceFormation: 'eager', votePattern: 'loyal', targetSelection: 'biggest_threat', idolUsage: 'strategic', nominationApproach: 'calculated', betrayalLikelihood: 0.15, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'moderate', tradeFrequency: 'moderate', tradeStyle: 'balanced', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.3 },
    visual: { nameStyle: 'casual', avatarStyle: 'classic', badgeLabel: 'ALLIANCE', badgeColor: '#10B981', teamBrandingFlavor: 'Strength in numbers', introCardStyle: 'standard', archetypeIcon: '🤝' },
    strengths: ['Social dominance', 'Vote control', 'Protected by allies'], weaknesses: ['Depends on others', 'Betrayal devastating', 'Not a solo threat'], intensity: 0.6,
  },
  loner: {
    id: 'loner', archetype: 'loner', displayName: 'The Loner', summary: 'Operates alone. No allies, no dependencies, no drama.',
    traits: { aggression: 0.4, patience: 0.6, loyalty: 0.1, flexibility: 0.5, randomness: 0.2, greed: 0.4, riskTolerance: 0.5, longTermThinking: 0.6, emotionalVolatility: 0.2, narrativeBias: 0.2, projectionTrust: 0.7, rookieBias: 0.5, starPlayerBias: 0.4, scarcityAwareness: 0.6, revengeTendency: 0.4, allianceStrength: 0.05, bluffTendency: 0.4, consistencyLevel: 0.7 },
    communication: { tone: 'cryptic', confidence: 0.6, snarkLevel: 0.3, dramaLevel: 0.1, seriousness: 0.7, responseLength: 'terse', trashTalkStyle: 'subtle', celebrationStyle: 'silent', winReaction: '...', lossReaction: 'Moving on.' },
    draftBehavior: { reachFrequency: 0.3, queueDiscipline: 0.7, positionPriority: ['RB', 'WR', 'QB'], starPreference: 0.4, rookieAggression: 0.5, auctionBidStyle: 'conservative', nominationStyle: 'value' },
    socialBehavior: { allianceFormation: 'avoids', votePattern: 'strategic', targetSelection: 'biggest_threat', idolUsage: 'conservative', nominationApproach: 'calculated', betrayalLikelihood: 0.3, juryBehavior: 'strategic' },
    rosterBehavior: { waiverActivity: 'moderate', tradeFrequency: 'rare', tradeStyle: 'balanced', lineupOptimization: 'daily_optimizer', cutAggressiveness: 0.4 },
    visual: { nameStyle: 'mysterious', avatarStyle: 'dark', badgeLabel: 'LONE WOLF', badgeColor: '#475569', teamBrandingFlavor: 'Solo mission', introCardStyle: 'minimal', archetypeIcon: '🐺' },
    strengths: ['No dependencies', 'Hard to read', 'Self-sufficient'], weaknesses: ['No vote protection', 'Easy target', 'Limited intel'], intensity: 0.5,
  },
  value_hunter: {
    id: 'value_hunter', archetype: 'value_hunter', displayName: 'The Value Hunter', summary: 'Always finds the best deal. Every pick, every trade, every waiver is about value.',
    traits: { aggression: 0.3, patience: 0.8, loyalty: 0.4, flexibility: 0.7, randomness: 0.1, greed: 0.3, riskTolerance: 0.4, longTermThinking: 0.8, emotionalVolatility: 0.1, narrativeBias: 0.1, projectionTrust: 0.8, rookieBias: 0.6, starPlayerBias: 0.2, scarcityAwareness: 0.9, revengeTendency: 0.1, allianceStrength: 0.5, bluffTendency: 0.3, consistencyLevel: 0.8 },
    communication: { tone: 'analytical', confidence: 0.7, snarkLevel: 0.2, dramaLevel: 0.1, seriousness: 0.8, responseLength: 'moderate', trashTalkStyle: 'subtle', celebrationStyle: 'humble', winReaction: 'Value wins again.', lossReaction: 'The process works long-term.' },
    draftBehavior: { reachFrequency: 0.05, queueDiscipline: 0.8, positionPriority: ['WR', 'RB', 'QB', 'TE'], starPreference: 0.2, rookieAggression: 0.6, auctionBidStyle: 'strategic', nominationStyle: 'value' },
    socialBehavior: { allianceFormation: 'selective', votePattern: 'strategic', targetSelection: 'biggest_threat', idolUsage: 'strategic', nominationApproach: 'calculated', betrayalLikelihood: 0.2, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'frequent', tradeStyle: 'opportunistic', lineupOptimization: 'daily_optimizer', cutAggressiveness: 0.4 },
    visual: { nameStyle: 'professional', avatarStyle: 'minimal', badgeLabel: 'VALUE', badgeColor: '#14B8A6', teamBrandingFlavor: 'Buy low, sell high', introCardStyle: 'minimal', archetypeIcon: '💎' },
    strengths: ['Best draft value', 'Smart trades', 'Efficient builds'], weaknesses: ['Misses boom players', 'Too conservative', 'Analysis paralysis'], intensity: 0.6,
  },
  win_now: {
    id: 'win_now', archetype: 'win_now', displayName: 'Win Now', summary: 'All-in on this season. Future be damned.',
    traits: { aggression: 0.8, patience: 0.1, loyalty: 0.5, flexibility: 0.4, randomness: 0.2, greed: 0.8, riskTolerance: 0.7, longTermThinking: 0.1, emotionalVolatility: 0.5, narrativeBias: 0.3, projectionTrust: 0.7, rookieBias: 0.1, starPlayerBias: 0.9, scarcityAwareness: 0.6, revengeTendency: 0.3, allianceStrength: 0.4, bluffTendency: 0.3, consistencyLevel: 0.6 },
    communication: { tone: 'sharp', confidence: 0.9, snarkLevel: 0.4, dramaLevel: 0.4, seriousness: 0.7, responseLength: 'terse', trashTalkStyle: 'bold', celebrationStyle: 'loud', winReaction: 'Championship or bust.', lossReaction: 'Not over yet.' },
    draftBehavior: { reachFrequency: 0.4, queueDiscipline: 0.6, positionPriority: ['RB', 'QB', 'WR', 'TE'], starPreference: 0.9, rookieAggression: 0.1, auctionBidStyle: 'aggressive', nominationStyle: 'strategic' },
    socialBehavior: { allianceFormation: 'selective', votePattern: 'strategic', targetSelection: 'biggest_threat', idolUsage: 'aggressive', nominationApproach: 'bold', betrayalLikelihood: 0.4, juryBehavior: 'strategic' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'frequent', tradeStyle: 'buyer', lineupOptimization: 'daily_optimizer', cutAggressiveness: 0.6 },
    visual: { nameStyle: 'dramatic', avatarStyle: 'classic', badgeLabel: 'WIN NOW', badgeColor: '#EAB308', teamBrandingFlavor: 'No tomorrow', introCardStyle: 'dramatic', archetypeIcon: '🏆' },
    strengths: ['Loaded roster', 'Trades for stars', 'Championship focused'], weaknesses: ['Mortgages future', 'No depth', 'One-year window'], intensity: 0.8,
  },
  rebuilder: {
    id: 'rebuilder', archetype: 'rebuilder', displayName: 'The Rebuilder', summary: 'Tearing it down to build it right. Picks and prospects over wins.',
    traits: { aggression: 0.2, patience: 0.95, loyalty: 0.3, flexibility: 0.6, randomness: 0.1, greed: 0.2, riskTolerance: 0.3, longTermThinking: 0.95, emotionalVolatility: 0.1, narrativeBias: 0.3, projectionTrust: 0.5, rookieBias: 0.9, starPlayerBias: 0.1, scarcityAwareness: 0.7, revengeTendency: 0.1, allianceStrength: 0.4, bluffTendency: 0.2, consistencyLevel: 0.8 },
    communication: { tone: 'calm', confidence: 0.6, snarkLevel: 0.1, dramaLevel: 0.1, seriousness: 0.7, responseLength: 'moderate', trashTalkStyle: 'none', celebrationStyle: 'humble', winReaction: 'Ahead of schedule.', lossReaction: 'Part of the plan.' },
    draftBehavior: { reachFrequency: 0.2, queueDiscipline: 0.7, positionPriority: ['WR', 'QB', 'RB'], starPreference: 0.1, rookieAggression: 0.9, auctionBidStyle: 'conservative', nominationStyle: 'value' },
    socialBehavior: { allianceFormation: 'eager', votePattern: 'loyal', targetSelection: 'strongest', idolUsage: 'conservative', nominationApproach: 'safe', betrayalLikelihood: 0.1, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'frequent', tradeStyle: 'seller', lineupOptimization: 'set_and_forget', cutAggressiveness: 0.3 },
    visual: { nameStyle: 'casual', avatarStyle: 'minimal', badgeLabel: 'REBUILDING', badgeColor: '#8B5CF6', teamBrandingFlavor: 'Trust the process', introCardStyle: 'standard', archetypeIcon: '🔨' },
    strengths: ['Draft capital king', 'Young roster', 'Future flexibility'], weaknesses: ['Loses now', 'Boring for opponents', 'Long payoff'], intensity: 0.5,
  },
  rookie_believer: {
    id: 'rookie_believer', archetype: 'rookie_believer', displayName: 'Rookie Believer', summary: 'Youth over everything. Every rookie is the next superstar.',
    traits: { aggression: 0.5, patience: 0.6, loyalty: 0.4, flexibility: 0.5, randomness: 0.3, greed: 0.4, riskTolerance: 0.6, longTermThinking: 0.7, emotionalVolatility: 0.4, narrativeBias: 0.6, projectionTrust: 0.4, rookieBias: 0.95, starPlayerBias: 0.2, scarcityAwareness: 0.5, revengeTendency: 0.2, allianceStrength: 0.5, bluffTendency: 0.3, consistencyLevel: 0.5 },
    communication: { tone: 'energetic', confidence: 0.7, snarkLevel: 0.2, dramaLevel: 0.4, seriousness: 0.4, responseLength: 'moderate', trashTalkStyle: 'subtle', celebrationStyle: 'loud', winReaction: 'The kids are alright!', lossReaction: 'Just wait till next year.' },
    draftBehavior: { reachFrequency: 0.5, queueDiscipline: 0.5, positionPriority: ['WR', 'RB', 'QB'], starPreference: 0.2, rookieAggression: 0.95, auctionBidStyle: 'aggressive', nominationStyle: 'value' },
    socialBehavior: { allianceFormation: 'eager', votePattern: 'loyal', targetSelection: 'strongest', idolUsage: 'conservative', nominationApproach: 'safe', betrayalLikelihood: 0.2, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'moderate', tradeStyle: 'buyer', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.4 },
    visual: { nameStyle: 'casual', avatarStyle: 'bright', badgeLabel: 'ROOKIE LOVER', badgeColor: '#06B6D4', teamBrandingFlavor: 'Next gen squad', introCardStyle: 'standard', archetypeIcon: '🌱' },
    strengths: ['Early on breakouts', 'Young roster', 'Future upside'], weaknesses: ['Overvalues youth', 'Ignores proven talent', 'Inconsistent'], intensity: 0.6,
  },
  veteran_loyalist: {
    id: 'veteran_loyalist', archetype: 'veteran_loyalist', displayName: 'Veteran Loyalist', summary: 'Proven talent only. No gambling on unknowns.',
    traits: { aggression: 0.4, patience: 0.5, loyalty: 0.9, flexibility: 0.3, randomness: 0.05, greed: 0.4, riskTolerance: 0.2, longTermThinking: 0.3, emotionalVolatility: 0.1, narrativeBias: 0.3, projectionTrust: 0.9, rookieBias: 0.05, starPlayerBias: 0.8, scarcityAwareness: 0.6, revengeTendency: 0.3, allianceStrength: 0.7, bluffTendency: 0.1, consistencyLevel: 0.9 },
    communication: { tone: 'calm', confidence: 0.7, snarkLevel: 0.2, dramaLevel: 0.1, seriousness: 0.8, responseLength: 'terse', trashTalkStyle: 'subtle', celebrationStyle: 'humble', winReaction: 'Experience wins.', lossReaction: 'Vets bounce back.' },
    draftBehavior: { reachFrequency: 0.1, queueDiscipline: 0.9, positionPriority: ['RB', 'QB', 'WR', 'TE'], starPreference: 0.8, rookieAggression: 0.05, auctionBidStyle: 'conservative', nominationStyle: 'value' },
    socialBehavior: { allianceFormation: 'eager', votePattern: 'loyal', targetSelection: 'weakest', idolUsage: 'conservative', nominationApproach: 'safe', betrayalLikelihood: 0.05, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'passive', tradeFrequency: 'rare', tradeStyle: 'balanced', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.2 },
    visual: { nameStyle: 'professional', avatarStyle: 'classic', badgeLabel: 'VETERAN', badgeColor: '#92400E', teamBrandingFlavor: 'Old school wins', introCardStyle: 'standard', archetypeIcon: '🎖️' },
    strengths: ['Reliable roster', 'Consistent floor', 'Predictable'], weaknesses: ['Aging roster', 'Missing breakouts', 'Declining assets'], intensity: 0.5,
  },
  defensive_specialist: {
    id: 'defensive_specialist', archetype: 'defensive_specialist', displayName: 'Defensive Specialist', summary: 'IDP-focused. Defense wins championships.',
    traits: { aggression: 0.4, patience: 0.6, loyalty: 0.5, flexibility: 0.5, randomness: 0.2, greed: 0.3, riskTolerance: 0.4, longTermThinking: 0.6, emotionalVolatility: 0.2, narrativeBias: 0.3, projectionTrust: 0.7, rookieBias: 0.4, starPlayerBias: 0.5, scarcityAwareness: 0.8, revengeTendency: 0.3, allianceStrength: 0.5, bluffTendency: 0.3, consistencyLevel: 0.7 },
    communication: { tone: 'analytical', confidence: 0.7, snarkLevel: 0.3, dramaLevel: 0.2, seriousness: 0.8, responseLength: 'moderate', trashTalkStyle: 'subtle', celebrationStyle: 'humble', winReaction: 'Defense delivered.', lossReaction: 'Offense let us down.' },
    draftBehavior: { reachFrequency: 0.3, queueDiscipline: 0.7, positionPriority: ['LB', 'DL', 'DB', 'RB', 'WR', 'QB'], starPreference: 0.5, rookieAggression: 0.4, auctionBidStyle: 'strategic', nominationStyle: 'strategic' },
    socialBehavior: { allianceFormation: 'selective', votePattern: 'strategic', targetSelection: 'biggest_threat', idolUsage: 'strategic', nominationApproach: 'calculated', betrayalLikelihood: 0.2, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'moderate', tradeStyle: 'balanced', lineupOptimization: 'daily_optimizer', cutAggressiveness: 0.4 },
    visual: { nameStyle: 'professional', avatarStyle: 'dark', badgeLabel: 'DEFENSE', badgeColor: '#0EA5E9', teamBrandingFlavor: 'Shutdown squad', introCardStyle: 'standard', archetypeIcon: '🛡️' },
    strengths: ['IDP edge', 'Overlooked value', 'Balanced roster'], weaknesses: ['Scoring format dependent', 'Niche strategy', 'Less exciting'], intensity: 0.6,
  },
  positional_purist: {
    id: 'positional_purist', archetype: 'positional_purist', displayName: 'Positional Purist', summary: 'Drafts by position priority. Fills needs in order.',
    traits: { aggression: 0.3, patience: 0.7, loyalty: 0.5, flexibility: 0.2, randomness: 0.05, greed: 0.3, riskTolerance: 0.2, longTermThinking: 0.5, emotionalVolatility: 0.1, narrativeBias: 0.1, projectionTrust: 0.8, rookieBias: 0.3, starPlayerBias: 0.4, scarcityAwareness: 0.95, revengeTendency: 0.1, allianceStrength: 0.5, bluffTendency: 0.1, consistencyLevel: 0.9 },
    communication: { tone: 'analytical', confidence: 0.6, snarkLevel: 0.1, dramaLevel: 0.05, seriousness: 0.9, responseLength: 'terse', trashTalkStyle: 'none', celebrationStyle: 'silent', winReaction: 'System works.', lossReaction: 'Variance happens.' },
    draftBehavior: { reachFrequency: 0.05, queueDiscipline: 0.95, positionPriority: ['RB', 'WR', 'QB', 'TE', 'K', 'DEF'], starPreference: 0.3, rookieAggression: 0.3, auctionBidStyle: 'conservative', nominationStyle: 'value' },
    socialBehavior: { allianceFormation: 'selective', votePattern: 'strategic', targetSelection: 'biggest_threat', idolUsage: 'strategic', nominationApproach: 'calculated', betrayalLikelihood: 0.15, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'moderate', tradeFrequency: 'moderate', tradeStyle: 'balanced', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.3 },
    visual: { nameStyle: 'professional', avatarStyle: 'minimal', badgeLabel: 'PURIST', badgeColor: '#64748B', teamBrandingFlavor: 'By the book', introCardStyle: 'minimal', archetypeIcon: '📐' },
    strengths: ['Complete roster', 'No position gaps', 'Predictable'], weaknesses: ['Inflexible', 'Misses BPA', 'Boring'], intensity: 0.4,
  },
  storyline_star: {
    id: 'storyline_star', archetype: 'storyline_star', displayName: 'Storyline Star', summary: 'Everything is content. Lives for the narrative.',
    traits: { aggression: 0.5, patience: 0.4, loyalty: 0.5, flexibility: 0.6, randomness: 0.4, greed: 0.4, riskTolerance: 0.6, longTermThinking: 0.4, emotionalVolatility: 0.7, narrativeBias: 0.95, projectionTrust: 0.3, rookieBias: 0.5, starPlayerBias: 0.6, scarcityAwareness: 0.4, revengeTendency: 0.6, allianceStrength: 0.5, bluffTendency: 0.6, consistencyLevel: 0.4 },
    communication: { tone: 'energetic', confidence: 0.8, snarkLevel: 0.5, dramaLevel: 0.9, seriousness: 0.3, responseLength: 'verbose', trashTalkStyle: 'bold', celebrationStyle: 'over_the_top', winReaction: 'WHAT A STORY!', lossReaction: 'The redemption arc begins.' },
    draftBehavior: { reachFrequency: 0.4, queueDiscipline: 0.4, positionPriority: ['QB', 'WR', 'RB'], starPreference: 0.7, rookieAggression: 0.5, auctionBidStyle: 'aggressive', nominationStyle: 'disruptive' },
    socialBehavior: { allianceFormation: 'eager', votePattern: 'emotional', targetSelection: 'personal', idolUsage: 'aggressive', nominationApproach: 'bold', betrayalLikelihood: 0.4, juryBehavior: 'emotional' },
    rosterBehavior: { waiverActivity: 'active', tradeFrequency: 'frequent', tradeStyle: 'opportunistic', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.5 },
    visual: { nameStyle: 'dramatic', avatarStyle: 'bright', badgeLabel: 'STAR', badgeColor: '#EC4899', teamBrandingFlavor: 'Main character energy', introCardStyle: 'flashy', archetypeIcon: '⭐' },
    strengths: ['Entertaining', 'Creates moments', 'Fan favorite'], weaknesses: ['Emotional decisions', 'Inconsistent', 'Drama over logic'], intensity: 0.8,
  },
  silent_assassin: {
    id: 'silent_assassin', archetype: 'silent_assassin', displayName: 'Silent Assassin', summary: 'Quiet. Deadly. You won\'t see it coming.',
    traits: { aggression: 0.5, patience: 0.8, loyalty: 0.3, flexibility: 0.6, randomness: 0.1, greed: 0.5, riskTolerance: 0.5, longTermThinking: 0.7, emotionalVolatility: 0.05, narrativeBias: 0.1, projectionTrust: 0.7, rookieBias: 0.4, starPlayerBias: 0.5, scarcityAwareness: 0.7, revengeTendency: 0.6, allianceStrength: 0.3, bluffTendency: 0.7, consistencyLevel: 0.8 },
    communication: { tone: 'cryptic', confidence: 0.7, snarkLevel: 0.4, dramaLevel: 0.1, seriousness: 0.8, responseLength: 'terse', trashTalkStyle: 'subtle', celebrationStyle: 'silent', winReaction: '*nods*', lossReaction: 'Noted.' },
    draftBehavior: { reachFrequency: 0.2, queueDiscipline: 0.8, positionPriority: ['RB', 'WR', 'QB', 'TE'], starPreference: 0.5, rookieAggression: 0.4, auctionBidStyle: 'strategic', nominationStyle: 'strategic' },
    socialBehavior: { allianceFormation: 'reluctant', votePattern: 'strategic', targetSelection: 'biggest_threat', idolUsage: 'strategic', nominationApproach: 'calculated', betrayalLikelihood: 0.5, juryBehavior: 'strategic' },
    rosterBehavior: { waiverActivity: 'moderate', tradeFrequency: 'moderate', tradeStyle: 'opportunistic', lineupOptimization: 'daily_optimizer', cutAggressiveness: 0.5 },
    visual: { nameStyle: 'mysterious', avatarStyle: 'dark', badgeLabel: 'ASSASSIN', badgeColor: '#1E293B', teamBrandingFlavor: 'You won\'t see it coming', introCardStyle: 'minimal', archetypeIcon: '🗡️' },
    strengths: ['Unreadable', 'Strategic betrayals', 'Efficient'], weaknesses: ['Low social capital', 'Surprise target', 'No allies in crisis'], intensity: 0.7,
  },
  fan_favorite: {
    id: 'fan_favorite', archetype: 'fan_favorite', displayName: 'Fan Favorite', summary: 'Everyone likes them. Positive, fun, and impossible to hate.',
    traits: { aggression: 0.2, patience: 0.6, loyalty: 0.8, flexibility: 0.5, randomness: 0.2, greed: 0.2, riskTolerance: 0.4, longTermThinking: 0.5, emotionalVolatility: 0.3, narrativeBias: 0.6, projectionTrust: 0.5, rookieBias: 0.5, starPlayerBias: 0.4, scarcityAwareness: 0.5, revengeTendency: 0.1, allianceStrength: 0.8, bluffTendency: 0.1, consistencyLevel: 0.6 },
    communication: { tone: 'energetic', confidence: 0.6, snarkLevel: 0.05, dramaLevel: 0.3, seriousness: 0.3, responseLength: 'moderate', trashTalkStyle: 'none', celebrationStyle: 'loud', winReaction: 'Love this game!', lossReaction: 'GG, see you next week!' },
    draftBehavior: { reachFrequency: 0.2, queueDiscipline: 0.6, positionPriority: ['WR', 'RB', 'QB', 'TE'], starPreference: 0.4, rookieAggression: 0.5, auctionBidStyle: 'conservative', nominationStyle: 'value' },
    socialBehavior: { allianceFormation: 'eager', votePattern: 'loyal', targetSelection: 'strongest', idolUsage: 'conservative', nominationApproach: 'safe', betrayalLikelihood: 0.05, juryBehavior: 'fair' },
    rosterBehavior: { waiverActivity: 'moderate', tradeFrequency: 'moderate', tradeStyle: 'balanced', lineupOptimization: 'weekly_tuner', cutAggressiveness: 0.3 },
    visual: { nameStyle: 'playful', avatarStyle: 'bright', badgeLabel: 'FAN FAVE', badgeColor: '#F472B6', teamBrandingFlavor: 'Good vibes only', introCardStyle: 'standard', archetypeIcon: '❤️' },
    strengths: ['Jury favorite', 'Strong alliances', 'Likable'], weaknesses: ['Too passive', 'Avoids conflict', 'Can be exploited'], intensity: 0.5,
  },
}

export function getPersonalityProfile(archetype: PersonalityArchetype): AIPersonalityProfile {
  return ARCHETYPES[archetype]
}

export function getAllArchetypes(): PersonalityArchetype[] {
  return Object.keys(ARCHETYPES) as PersonalityArchetype[]
}

export function getRandomArchetype(): PersonalityArchetype {
  const keys = getAllArchetypes()
  return keys[Math.floor(Math.random() * keys.length)]
}

export function getArchetypesForLeagueType(leagueType: string): PersonalityArchetype[] {
  if (leagueType === 'survivor' || leagueType === 'big_brother') {
    return ['villain', 'strategist', 'underdog', 'alpha', 'wildcard', 'chaos_agent', 'alliance_builder', 'loner', 'storyline_star', 'silent_assassin', 'fan_favorite']
  }
  return getAllArchetypes()
}
