[{
	"resource": "/c:/Users/Guap_/allfantasy-v2-main/app/api/user/trade-profile/route.ts",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'user' does not exist on type '{}'.",
	"source": "ts",
	"startLineNumber": 10,
	"startColumn": 58,
	"endLineNumber": 10,
	"endColumn": 62,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Guap_/allfantasy-v2-main/app/api/user/trade-profile/route.ts",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'user' does not exist on type '{}'.",
	"source": "ts",
	"startLineNumber": 10,
	"startColumn": 26,
	"endLineNumber": 10,
	"endColumn": 30,
	"modelVersionId": 5,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Guap_/allfantasy-v2-main/app/api/user/active-league/route.ts",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'leagueMember' does not exist on type 'DynamicClientExtensionThis<TypeMap<InternalArgs & { result: {}; model: {}; query: {}; client: {}; }, PrismaClientOptions>, TypeMapCb, { result: {}; model: {}; query: {}; client: {}; }, {}>'.",
	"source": "ts",
	"startLineNumber": 59,
	"startColumn": 37,
	"endLineNumber": 59,
	"endColumn": 49,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Guap_/allfantasy-v2-main/app/api/user/active-league/route.ts",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'user' does not exist on type '{}'.",
	"source": "ts",
	"startLineNumber": 10,
	"startColumn": 58,
	"endLineNumber": 10,
	"endColumn": 62,
	"modelVersionId": 2,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Guap_/allfantasy-v2-main/app/api/user/active-league/route.ts",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'user' does not exist on type '{}'.",
	"source": "ts",
	"startLineNumber": 10,
	"startColumn": 26,
	"endLineNumber": 10,
	"endColumn": 30,
	"modelVersionId": 2,
	"origin": "extHost1"
}]