"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { Share2, RefreshCw, Loader2 } from "lucide-react"

type Props = {
  episodeId: string
  title: string
  script: string
  status: string
  playbackUrl: string | null
}

export default function FantasyMediaPlayerClient({
  episodeId,
  title,
  script,
  status: initialStatus,
  playbackUrl: initialPlaybackUrl,
}: Props) {
  const [status, setStatus] = useState(initialStatus)
  const [playbackUrl, setPlaybackUrl] = useState<string | null>(initialPlaybackUrl)
  const [shareDone, setShareDone] = useState(false)
  const [shareError, setShareError] = useState<string | null>(null)

  const shareUrl = typeof window !== "undefined" ? `${window.location.origin}/fantasy-media/${episodeId}` : ""

  useEffect(() => {
    if (status !== "generating") return
    const t = setInterval(async () => {
      try {
        const res = await fetch(`/api/fantasy-media/episodes/${episodeId}/status`)
        const data = await res.json()
        if (data.status) setStatus(data.status)
        if (data.playbackUrl) setPlaybackUrl(data.playbackUrl)
      } catch {
        // keep polling
      }
    }, 5000)
    return () => clearInterval(t)
  }, [episodeId, status])

  const handleRefreshStatus = async () => {
    try {
      const res = await fetch(`/api/fantasy-media/episodes/${episodeId}/status`)
      const data = await res.json()
      if (data.status) setStatus(data.status)
      if (data.playbackUrl) setPlaybackUrl(data.playbackUrl)
    } catch {
      // ignore
    }
  }

  const handleShare = async () => {
    setShareError(null)
    setShareDone(false)
    try {
      if (typeof navigator !== "undefined" && navigator.share && navigator.canShare?.({ url: shareUrl })) {
        await navigator.share({
          title,
          text: `Fantasy video: ${title}`,
          url: shareUrl,
        })
        setShareDone(true)
      } else if (typeof navigator !== "undefined" && navigator.clipboard) {
        await navigator.clipboard.writeText(shareUrl)
        setShareDone(true)
      }
    } catch (e: unknown) {
      if ((e as { name?: string })?.name !== "AbortError") setShareError("Share failed")
    }
  }

  const canPlay = status === "completed" && playbackUrl

  return (
    <div className="space-y-6">
      <Link href="/fantasy-media" className="text-sm text-white/60 hover:text-white/80 transition">
        ← All videos
      </Link>

      <h1 className="text-xl font-bold text-white">{title}</h1>

      <p className="text-xs text-white/50">
        Status: <span className="capitalize">{status}</span>
      </p>

      {status === "generating" && (
        <div className="flex items-center gap-2 rounded-xl border border-cyan-500/30 bg-cyan-500/10 px-4 py-3 text-sm text-cyan-200">
          <Loader2 className="h-4 w-4 animate-spin" />
          Video is being generated by HeyGen. This may take a few minutes.
        </div>
      )}

      {status === "failed" && (
        <div className="rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">
          Video generation failed. You can try again from the list.
        </div>
      )}

      {canPlay && (
        <div className="rounded-xl overflow-hidden border border-white/10 bg-black/30">
          <video
            src={playbackUrl}
            controls
            playsInline
            className="w-full aspect-video"
            preload="metadata"
          >
            Your browser does not support video playback.
          </video>
        </div>
      )}

      <div className="flex flex-wrap items-center gap-2">
        {status === "generating" && (
          <button
            type="button"
            onClick={handleRefreshStatus}
            className="flex items-center gap-2 rounded-xl border border-white/20 px-4 py-2 text-sm font-medium text-white hover:bg-white/10"
            aria-label="Refresh status"
          >
            <RefreshCw className="h-4 w-4" />
            Refresh status
          </button>
        )}
        <button
          type="button"
          onClick={handleShare}
          className="flex items-center gap-2 rounded-xl border border-white/20 px-4 py-2 text-sm font-medium text-white/90 hover:bg-white/10 transition"
          aria-label="Share or copy link"
        >
          <Share2 className="h-4 w-4" />
          {shareDone ? "Copied!" : "Copy link"}
        </button>
      </div>

      {shareError && <p className="text-sm text-red-300">{shareError}</p>}

      <div className="rounded-xl border border-white/10 bg-white/5 p-4">
        <p className="text-xs font-medium text-white/50 uppercase tracking-wider mb-2">Script</p>
        <p className="text-sm text-white/80 whitespace-pre-wrap">{script}</p>
      </div>
    </div>
  )
}
