/** MLS / common club geocoding strings for OpenWeather geocode API (city-level is sufficient for match-day mesoscale). */
export const SOCCER_TEAM_GEOCODE_QUERY: Record<string, string> = {
  ATL: 'Atlanta, GA, USA',
  ATX: 'Austin, TX, USA',
  CHI: 'Chicago, IL, USA',
  CIN: 'Cincinnati, OH, USA',
  CLB: 'Columbus, OH, USA',
  COL: 'Denver, CO, USA',
  DAL: 'Dallas, TX, USA',
  DC: 'Washington, DC, USA',
  HOU: 'Houston, TX, USA',
  LAFC: 'Los Angeles, CA, USA',
  LAG: 'Los Angeles, CA, USA',
  MIA: 'Fort Lauderdale, FL, USA',
  MIN: 'Saint Paul, MN, USA',
  MTL: 'Montreal, QC, Canada',
  NSH: 'Nashville, TN, USA',
  NE: 'Foxborough, MA, USA',
  NYC: 'New York, NY, USA',
  NYRB: 'Harrison, NJ, USA',
  ORL: 'Orlando, FL, USA',
  PHI: 'Chester, PA, USA',
  POR: 'Portland, OR, USA',
  RSL: 'Sandy, UT, USA',
  SEA: 'Seattle, WA, USA',
  SJ: 'San Jose, CA, USA',
  SKC: 'Kansas City, KS, USA',
  STL: 'St. Louis, MO, USA',
  TOR: 'Toronto, ON, Canada',
  VAN: 'Vancouver, BC, Canada',
}
