/**
 * E.1 — classify a candidate player headshot URL into one of:
 *   - 'headshot'              : real player photo from a CDN (sleepercdn, espncdn /headshots/, etc.)
 *   - 'team_logo_badge_only'  : team logo (e.g. /teamLogos/atl.png). Should NEVER be the main avatar.
 *   - 'synthesized'           : data: URI generated by the resolver as a placeholder (not a real photo).
 *   - 'null'                  : empty / not provided.
 *
 * The audit found that the resolver populates `display.assets.headshotUrl` with a mix of real
 * headshots, generic ESPN team logos, and synthesized SVG data URIs. The browser loads the
 * latter two successfully so the `<img>.onError` fallback never fires; the row ends up showing
 * a team logo or a stylized "AF" letter where a player photo should be. PlayerAvatar uses this
 * classifier so we can skip synthesized + team-logo URLs and fall through to initials.
 */

export type AvatarSource = 'headshot' | 'team_logo_badge_only' | 'synthesized' | 'null'

export function classifyAvatarSource(url: string | null | undefined): AvatarSource {
  if (!url) return 'null'
  const trimmed = String(url).trim()
  if (trimmed.length === 0) return 'null'
  if (trimmed.startsWith('data:')) return 'synthesized'
  // ESPN, Sleeper, and most providers use distinct paths for player headshots vs team logos.
  // Match on /teamLogos/ or /teamLogo/ (singular) to be safe.
  if (/\/teamLogos?\//i.test(trimmed)) return 'team_logo_badge_only'
  // Anything else with http(s) is treated as a real headshot URL.
  if (/^https?:\/\//i.test(trimmed)) return 'headshot'
  // Relative paths or unknown schemes — treat as null so we fall back to initials.
  return 'null'
}

/**
 * F.1 (DEF avatar special case) — true when this row represents a team defense
 * and therefore the team logo should be promoted to the primary avatar slot.
 * Defenses don't have a player headshot; a logo IS the correct primary asset.
 *
 * Returns true only for the literal `'DEF'` position (case- and whitespace-
 * tolerant). All other positions — including `'D/ST'` aliases that the
 * normalizer should already have collapsed to `'DEF'`, and IDP positions
 * like `DL`/`LB`/`DB`/`CB`/`S` — return false. Those represent individual
 * players who SHOULD have a real headshot, and we never want to silently
 * substitute a team logo for them.
 */
export function isDefRowForAvatar(position: string | null | undefined): boolean {
  return String(position ?? '').trim().toUpperCase() === 'DEF'
}

/** Compute up-to-2-letter initials from a display name. Single-name players → 1 letter. */
export function initialsFor(displayName: string | null | undefined): string {
  const name = (displayName ?? '').trim()
  if (!name) return '?'
  const parts = name.split(/\s+/).filter(Boolean)
  if (parts.length === 0) return '?'
  if (parts.length === 1) return parts[0]!.charAt(0).toUpperCase() || '?'
  const first = parts[0]!.charAt(0).toUpperCase()
  const last = parts[parts.length - 1]!.charAt(0).toUpperCase()
  return `${first}${last}` || '?'
}
