/**
 * Subscription and entitlement types for gating (useEntitlement, LockedFeatureCard).
 * PROMPT 287 — Monetization QA; single source for feature IDs and plan mapping.
 */

/** Feature IDs used for hasAccess(featureId). Matches useEntitlement plan mapping. */
export type SubscriptionFeatureId =
  | 'trade_analyzer'
  | 'ai_chat'
  | 'ai_waivers'
  | 'planning_tools'
  | 'player_ai_recommendations'
  | 'matchup_explanations'
  | 'player_comparison_explanations'
  | 'advanced_scoring'
  | 'advanced_playoff_setup'
  | 'ai_collusion_detection'
  | 'ai_tanking_detection'
  | 'storyline_creation'
  | 'league_rankings'
  | 'draft_rankings'
  | 'ai_team_managers'
  | 'commissioner_automation'
  | 'draft_strategy_build'
  | 'draft_prep'
  | 'future_planning'
  | 'multi_year_strategy'
  | 'draft_board_intelligence'
  | 'roster_construction_planning'
  | 'ai_planning_3_5_year'
  | 'guillotine_ai'
  | 'salary_cap_ai'
  | 'survivor_ai'
  | 'zombie_ai'
  // UI / monetization catalog keys (same strings as former FeatureKey — unified with matrix IDs)
  | 'commissioner_ai_tools'
  | 'commissioner_ai_narration'
  | 'commissioner_ai_recap'
  | 'commissioner_ai_copilot'
  | 'commissioner_ai_jury_briefing'
  | 'commissioner_nomination_analysis'
  | 'commissioner_pov_analysis'
  | 'commissioner_power_rankings'
  | 'commissioner_fairness_audit'
  | 'commissioner_constitution_generator'
  | 'commissioner_devy_scouting'
  | 'commissioner_idp_analysis'
  | 'commissioner_cap_advice'
  | 'commissioner_c2c_scouting'
  | 'commissioner_weather_projections'
  | 'pro_draft_ai'
  | 'pro_waiver_ai'
  | 'pro_trade_ai'
  | 'pro_lineup_optimizer'
  | 'pro_start_sit'
  | 'pro_matchup_analysis'
  | 'pro_player_comparison'
  | 'pro_af_projections'
  | 'pro_snap_analysis'
  | 'war_room_dynasty_projections'
  | 'war_room_devy_rankings'
  | 'war_room_draft_strategy'
  | 'war_room_pipeline_analysis'

/** Plan slugs returned by entitlements API; used for hasAccess. */
export type SubscriptionPlanId = 'pro' | 'commissioner' | 'war_room' | 'all_access'

/** Entitlement status from GET /api/subscription/entitlements */
export type EntitlementStatus = 'active' | 'grace' | 'past_due' | 'expired' | 'none'
