import type { LineupRosterPlayer } from './types'

/** Demo roster for empty-state / showcase — aligns with NFL default slots. */
export const SAMPLE_NFL_ROSTER: LineupRosterPlayer[] = [
  {
    id: 'p1',
    name: 'Josh Allen',
    positions: ['QB'],
    projectedPoints: 24.2,
    team: 'BUF',
    opponent: 'vs MIA',
    gameTime: 'Sun 1:00 PM',
    injuryStatus: 'Healthy',
    trend: 'up',
  },
  {
    id: 'p2',
    name: 'Bijan Robinson',
    positions: ['RB'],
    projectedPoints: 18.4,
    team: 'ATL',
    opponent: '@ TB',
    gameTime: 'Sun 1:00 PM',
    injuryStatus: 'Healthy',
    trend: 'flat',
    isRookie: false,
  },
  {
    id: 'p3',
    name: 'Saquon Barkley',
    positions: ['RB'],
    projectedPoints: 16.1,
    team: 'PHI',
    opponent: 'vs NYG',
    gameTime: 'Sun 4:25 PM',
    injuryStatus: 'Questionable',
    trend: 'down',
  },
  {
    id: 'p4',
    name: 'Amon-Ra St. Brown',
    positions: ['WR'],
    projectedPoints: 17.8,
    team: 'DET',
    opponent: 'vs CHI',
    gameTime: 'Sun 1:00 PM',
    injuryStatus: 'Healthy',
    trend: 'up',
  },
  {
    id: 'p5',
    name: 'Mike Evans',
    positions: ['WR'],
    projectedPoints: 14.2,
    team: 'TB',
    opponent: 'vs ATL',
    gameTime: 'Sun 1:00 PM',
    injuryStatus: 'Healthy',
    trend: 'flat',
  },
  {
    id: 'p6',
    name: 'Travis Kelce',
    positions: ['TE'],
    projectedPoints: 12.9,
    team: 'KC',
    opponent: '@ LV',
    gameTime: 'Sun 8:20 PM',
    injuryStatus: 'Healthy',
    trend: 'up',
    isVeteran: true,
  },
  {
    id: 'p7',
    name: 'James Cook',
    positions: ['RB'],
    projectedPoints: 13.5,
    team: 'BUF',
    opponent: 'vs MIA',
    gameTime: 'Sun 1:00 PM',
    injuryStatus: 'Healthy',
    trend: 'up',
  },
  {
    id: 'p8',
    name: 'Bills D/ST',
    positions: ['DST'],
    projectedPoints: 9.1,
    team: 'BUF',
    opponent: 'vs MIA',
    gameTime: 'Sun 1:00 PM',
    injuryStatus: 'Healthy',
    trend: 'flat',
  },
  {
    id: 'p9',
    name: 'Jake Ferguson',
    positions: ['TE'],
    projectedPoints: 8.4,
    team: 'DAL',
    opponent: '@ WAS',
    gameTime: 'Sun 1:00 PM',
    injuryStatus: 'Healthy',
    trend: 'flat',
  },
]

export const SAMPLE_ROSTER_SLOTS = ['QB', 'RB', 'RB', 'WR', 'WR', 'TE', 'FLEX', 'DST']
