/**
 * AI Action Registry
 * Static metadata for every AIActionType — labels, safety class, required permissions,
 * destructive flag, valid surfaces, and prefill targets.
 * Import AI_ACTION_REGISTRY to inspect any action without runtime context.
 */

import type {
  AIActionType,
  AIActionSafetyClass,
  AIActionPermission,
  AIActionSurface,
} from './AIActionModel'

export interface ActionMeta {
  label: string
  description: string
  safetyClass: AIActionSafetyClass
  requiredPermissions: AIActionPermission[]
  requiresCommissioner: boolean
  requiresPremium: boolean
  isDestructive: boolean
  surfaces: Array<AIActionSurface | string>
  /** Target workflow identifier for prefill */
  prefillTarget?: string
  /** Label shown on the premium lock badge */
  premiumBadgeLabel?: string
}

export const AI_ACTION_REGISTRY: Record<AIActionType, ActionMeta> = {
  // ── Draft ──────────────────────────────────────────────────────────────────
  queue_player: {
    label: 'Queue Player',
    description: 'Add this player to your draft queue',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['draft_room'],
    prefillTarget: 'draft_queue',
  },
  auto_queue_best_3: {
    label: 'Auto-Queue Best 3',
    description: 'Automatically add the top 3 AI-recommended players to your queue',
    safetyClass: 'confirmed',
    requiredPermissions: ['member', 'premium'],
    requiresCommissioner: false,
    requiresPremium: true,
    isDestructive: false,
    surfaces: ['draft_room'],
    prefillTarget: 'draft_queue',
    premiumBadgeLabel: 'Pro',
  },
  draft_player: {
    label: 'Draft This Player',
    description: "Stage this player as your next pick when it's your turn",
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['draft_room'],
    prefillTarget: 'draft_pick',
  },
  set_auction_bid: {
    label: 'Set Auction Bid',
    description: 'Pre-fill your max bid for this player in the auction room',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['draft_room'],
    prefillTarget: 'auction_bidder',
  },
  bookmark_player: {
    label: 'Bookmark Player',
    description: 'Save this player to your draft watchlist',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['draft_room', 'player_page'],
    prefillTarget: 'draft_bookmarks',
  },
  compare_draft_options: {
    label: 'Compare Options',
    description: 'Compare this player against alternatives at this pick position',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['draft_room'],
    prefillTarget: 'player_compare_modal',
  },

  // ── Waiver ─────────────────────────────────────────────────────────────────
  claim_player: {
    label: 'Claim Now',
    description: 'Submit a waiver claim for this player',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['waiver_wire', 'roster', 'player_page'],
    prefillTarget: 'waiver_claim_modal',
  },
  add_to_watchlist: {
    label: 'Add to Watchlist',
    description: 'Save this player to monitor without claiming',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['waiver_wire', 'player_page', 'roster'],
    prefillTarget: 'watchlist',
  },
  set_faab_bid: {
    label: 'Set FAAB Bid',
    description: 'Pre-fill a FAAB bid amount for this player',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['waiver_wire', 'player_page'],
    prefillTarget: 'faab_bid_modal',
  },
  drop_player_for_claim: {
    label: 'Drop + Claim',
    description: 'Drop a suggested player and claim this one in a single move',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: true,
    surfaces: ['waiver_wire'],
    prefillTarget: 'waiver_claim_modal',
  },
  compare_claims: {
    label: 'Compare Claims',
    description: 'Compare this waiver claim against other available players',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['waiver_wire'],
    prefillTarget: 'player_compare_modal',
  },
  save_waiver_plan: {
    label: 'Save Waiver Plan',
    description: 'Save this AI waiver strategy for later in the week',
    safetyClass: 'instant',
    requiredPermissions: ['member', 'premium'],
    requiresCommissioner: false,
    requiresPremium: true,
    isDestructive: false,
    surfaces: ['waiver_wire'],
    prefillTarget: 'saved_plans',
    premiumBadgeLabel: 'Pro',
  },

  // ── Lineup ─────────────────────────────────────────────────────────────────
  start_player: {
    label: 'Start Player',
    description: 'Move this player into your starting lineup',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster', 'matchup', 'player_page'],
    prefillTarget: 'lineup_editor',
  },
  bench_player: {
    label: 'Bench Player',
    description: 'Move this player to your bench',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster', 'matchup', 'player_page'],
    prefillTarget: 'lineup_editor',
  },
  optimize_lineup: {
    label: 'Optimize Lineup',
    description: 'Apply AI-optimized lineup for maximum projected points',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster', 'matchup'],
    prefillTarget: 'lineup_editor',
  },
  optimize_bench: {
    label: 'Optimize Bench',
    description: 'Reorder bench for optimal flex and streamer coverage',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster'],
    prefillTarget: 'lineup_editor',
  },
  swap_players: {
    label: 'Swap Players',
    description: 'Swap the suggested players in and out of your starting lineup',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster', 'matchup'],
    prefillTarget: 'lineup_editor',
  },
  save_lineup: {
    label: 'Save Lineup',
    description: 'Commit the suggested lineup changes',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster', 'matchup'],
    prefillTarget: 'lineup_editor',
  },

  // ── Trade ──────────────────────────────────────────────────────────────────
  analyze_trade: {
    label: 'Analyze Trade',
    description: "Get Chimmy's full trade fairness and value analysis",
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['trade_center', 'roster', 'player_page'],
    prefillTarget: 'trade_analyzer_modal',
  },
  propose_trade: {
    label: 'Propose Trade',
    description: 'Open trade composer with AI-suggested assets pre-loaded',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['trade_center', 'roster', 'player_page'],
    prefillTarget: 'trade_composer',
  },
  generate_counter: {
    label: 'Generate Counter',
    description: 'Let Chimmy propose a counter-offer to this trade',
    safetyClass: 'instant',
    requiredPermissions: ['member', 'premium'],
    requiresCommissioner: false,
    requiresPremium: true,
    isDestructive: false,
    surfaces: ['trade_center'],
    prefillTarget: 'trade_composer',
    premiumBadgeLabel: 'Pro',
  },
  save_counter_draft: {
    label: 'Save Counter Draft',
    description: 'Save this auto-generated counter proposal to review later',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['trade_center'],
    prefillTarget: 'saved_trades',
  },
  ai_trade_review: {
    label: 'Send to AI Review',
    description: 'Get an in-depth private AI review of this trade',
    safetyClass: 'instant',
    requiredPermissions: ['member', 'premium'],
    requiresCommissioner: false,
    requiresPremium: true,
    isDestructive: false,
    surfaces: ['trade_center'],
    prefillTarget: 'chimmy_chat',
    premiumBadgeLabel: 'Pro',
  },
  share_trade_summary: {
    label: 'Share in Chat',
    description: 'Post this trade analysis to your league chat',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['trade_center', 'league_chat'],
    prefillTarget: 'league_chat_composer',
  },

  // ── Roster ─────────────────────────────────────────────────────────────────
  drop_player: {
    label: 'Drop Player',
    description: 'Release this player from your roster',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: true,
    surfaces: ['roster', 'player_page'],
    prefillTarget: 'drop_confirm_modal',
  },
  move_to_bench: {
    label: 'Move to Bench',
    description: 'Move this player to your bench slot',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster'],
    prefillTarget: 'lineup_editor',
  },
  move_to_ir: {
    label: 'Move to IR',
    description: 'Place this player on injured reserve',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster', 'player_page'],
    prefillTarget: 'roster_move_modal',
  },
  move_to_il: {
    label: 'Move to IL',
    description: 'Place this player on the injured list',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster', 'player_page'],
    prefillTarget: 'roster_move_modal',
  },
  move_to_taxi: {
    label: 'Move to Taxi Squad',
    description: 'Move this player to your taxi squad',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster'],
    prefillTarget: 'roster_move_modal',
  },
  move_to_devy: {
    label: 'Move to Devy',
    description: 'Move this player to your developmental squad',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster'],
    prefillTarget: 'roster_move_modal',
  },
  compare_replacement: {
    label: 'Compare Replacements',
    description: 'See who is available to replace this player on waivers or in a trade',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster', 'player_page', 'waiver_wire'],
    prefillTarget: 'player_compare_modal',
  },
  flag_trade_block: {
    label: 'Trade Block',
    description: 'Mark this player as available for trade',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster', 'player_page'],
    prefillTarget: 'trade_block',
  },
  save_future_move: {
    label: 'Save for Later',
    description: 'Save this roster move to act on before the deadline',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['roster'],
    prefillTarget: 'saved_moves',
  },

  // ── Matchup ────────────────────────────────────────────────────────────────
  simulate_matchup: {
    label: 'Run Simulation',
    description: 'Run a Monte Carlo simulation of this matchup',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['matchup'],
    prefillTarget: 'matchup_simulator',
  },
  try_alternate_starter: {
    label: 'Try Alternate Starter',
    description: 'Preview how a starter swap affects your projected score',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['matchup'],
    prefillTarget: 'lineup_editor',
  },
  optimize_ceiling: {
    label: 'Optimize for Ceiling',
    description: 'Maximize your upside this week — high-risk, high-reward lineup',
    safetyClass: 'confirmed',
    requiredPermissions: ['member', 'premium'],
    requiresCommissioner: false,
    requiresPremium: true,
    isDestructive: false,
    surfaces: ['matchup', 'roster'],
    prefillTarget: 'lineup_editor',
    premiumBadgeLabel: 'Pro',
  },
  optimize_floor: {
    label: 'Optimize for Floor',
    description: 'Maximize your safe floor this week — low-risk, steady lineup',
    safetyClass: 'confirmed',
    requiredPermissions: ['member', 'premium'],
    requiresCommissioner: false,
    requiresPremium: true,
    isDestructive: false,
    surfaces: ['matchup', 'roster'],
    prefillTarget: 'lineup_editor',
    premiumBadgeLabel: 'Pro',
  },
  optimize_categories: {
    label: 'Optimize Categories',
    description: 'Target specific scoring categories to win this matchup',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['matchup'],
    prefillTarget: 'lineup_editor',
  },
  save_matchup_strategy: {
    label: 'Save Strategy',
    description: 'Save this matchup strategy for your records',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['matchup'],
    prefillTarget: 'saved_strategies',
  },

  // ── Commissioner ───────────────────────────────────────────────────────────
  draft_announcement: {
    label: 'Draft Announcement',
    description: 'Generate and post a league announcement with AI-drafted copy',
    safetyClass: 'confirmed',
    requiredPermissions: ['commissioner'],
    requiresCommissioner: true,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['commissioner_panel', 'league_home', 'league_chat'],
    prefillTarget: 'announcement_composer',
  },
  post_recap: {
    label: 'Post Weekly Recap',
    description: 'Generate and post an AI-written weekly league recap',
    safetyClass: 'confirmed',
    requiredPermissions: ['commissioner', 'commissioner_subscription'],
    requiresCommissioner: true,
    requiresPremium: true,
    isDestructive: false,
    surfaces: ['commissioner_panel', 'league_home'],
    prefillTarget: 'announcement_composer',
    premiumBadgeLabel: 'Commissioner+',
  },
  send_warning: {
    label: 'Send Warning',
    description: 'Send a formal warning to a manager about activity or conduct',
    safetyClass: 'confirmed',
    requiredPermissions: ['commissioner'],
    requiresCommissioner: true,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['commissioner_panel'],
    prefillTarget: 'warning_composer',
  },
  approve_issue: {
    label: 'Review Issue',
    description: 'Review and resolve a flagged league issue',
    safetyClass: 'confirmed',
    requiredPermissions: ['commissioner'],
    requiresCommissioner: true,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['commissioner_panel'],
    prefillTarget: 'issue_reviewer',
  },
  generate_rule_update: {
    label: 'Generate Rule Update',
    description: 'Draft an AI-written league rule change message',
    safetyClass: 'confirmed',
    requiredPermissions: ['commissioner', 'commissioner_subscription'],
    requiresCommissioner: true,
    requiresPremium: true,
    isDestructive: false,
    surfaces: ['commissioner_panel'],
    prefillTarget: 'announcement_composer',
    premiumBadgeLabel: 'Commissioner+',
  },
  open_health_report: {
    label: 'League Health Report',
    description: 'Open the full AI league health and activity analysis',
    safetyClass: 'instant',
    requiredPermissions: ['commissioner'],
    requiresCommissioner: true,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['commissioner_panel', 'league_home'],
    prefillTarget: 'league_health_modal',
  },

  // ── Discovery ──────────────────────────────────────────────────────────────
  join_league: {
    label: 'Join League',
    description: 'Start the onboarding flow to join this matched league',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['discovery'],
    prefillTarget: 'league_join_flow',
  },
  save_league: {
    label: 'Save League',
    description: 'Save this league to your shortlist',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['discovery'],
    prefillTarget: 'saved_leagues',
  },
  compare_leagues: {
    label: 'Compare Options',
    description: 'Compare this league against other AI-matched leagues',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['discovery'],
    prefillTarget: 'league_compare_modal',
  },
  ask_why_fit: {
    label: 'Why This League?',
    description: 'Ask Chimmy why this league is a strong match for you',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['discovery'],
    prefillTarget: 'chimmy_chat',
  },

  // ── General ────────────────────────────────────────────────────────────────
  open_deep_dive: {
    label: 'Deep Dive',
    description: 'Open the full AI analysis for this recommendation',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: [
      'dashboard', 'league_home', 'roster', 'matchup',
      'waiver_wire', 'trade_center', 'player_page', 'team_page',
    ],
    prefillTarget: 'deep_dive_modal',
  },
  save_recommendation: {
    label: 'Save Recommendation',
    description: 'Save this AI recommendation to review later',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['dashboard', 'roster', 'waiver_wire', 'trade_center', 'matchup'],
    prefillTarget: 'saved_recommendations',
  },
  schedule_reminder: {
    label: 'Set Reminder',
    description: 'Schedule a reminder to act on this recommendation before deadline',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['dashboard', 'roster', 'waiver_wire'],
    prefillTarget: 'reminder_modal',
  },
  compare_alternatives: {
    label: 'Compare Alternatives',
    description: 'Compare this recommendation against other available options',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['dashboard', 'waiver_wire', 'trade_center', 'player_page'],
    prefillTarget: 'player_compare_modal',
  },
  post_to_league_chat: {
    label: 'Post to League Chat',
    description: 'Share this AI insight with your league',
    safetyClass: 'confirmed',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['league_home', 'league_chat', 'trade_center', 'matchup'],
    prefillTarget: 'league_chat_composer',
  },
  start_simulation: {
    label: 'Start Simulation',
    description: 'Run an AI scenario simulation for this context',
    safetyClass: 'instant',
    requiredPermissions: ['member'],
    requiresCommissioner: false,
    requiresPremium: false,
    isDestructive: false,
    surfaces: ['matchup', 'roster', 'trade_center'],
    prefillTarget: 'scenario_simulator',
  },
}

/** Look up metadata for an action type. Returns undefined for unknown types. */
export function getActionMeta(type: AIActionType): ActionMeta {
  return AI_ACTION_REGISTRY[type]
}

/** All action types grouped by safety class */
export const INSTANT_ACTIONS = (Object.keys(AI_ACTION_REGISTRY) as AIActionType[]).filter(
  (t) => AI_ACTION_REGISTRY[t].safetyClass === 'instant',
)

export const CONFIRMED_ACTIONS = (Object.keys(AI_ACTION_REGISTRY) as AIActionType[]).filter(
  (t) => AI_ACTION_REGISTRY[t].safetyClass === 'confirmed',
)

export const DESTRUCTIVE_ACTION_TYPES = (Object.keys(AI_ACTION_REGISTRY) as AIActionType[]).filter(
  (t) => AI_ACTION_REGISTRY[t].isDestructive,
)
