import type { Prisma, PrismaClient } from '@prisma/client'

const CONFIGS: {
  sport: string
  lineupFrequency: string
  scoringType: string
  hasIR: boolean
  hasTaxi: boolean
  hasBye: boolean
  maxRosterSize: number
  defaultPositions: Prisma.InputJsonValue
  statCategories: Prisma.InputJsonValue
}[] = [
  {
    sport: 'NFL',
    lineupFrequency: 'weekly',
    scoringType: 'points',
    hasIR: true,
    hasTaxi: true,
    hasBye: true,
    maxRosterSize: 25,
    defaultPositions: [
      { slot: 'QB', eligible: ['QB'], count: 1 },
      { slot: 'RB', eligible: ['RB'], count: 2 },
      { slot: 'WR', eligible: ['WR'], count: 2 },
      { slot: 'TE', eligible: ['TE'], count: 1 },
      { slot: 'FLEX', eligible: ['RB', 'WR', 'TE'], count: 1 },
      { slot: 'K', eligible: ['K'], count: 1 },
      { slot: 'DEF', eligible: ['DEF'], count: 1 },
      { slot: 'BN', eligible: ['*'], count: 6 },
      { slot: 'IR', eligible: ['*'], count: 2 },
    ],
    statCategories: [
      { key: 'pass_yds', label: 'Pass Yds', points: 0.04 },
      { key: 'pass_td', label: 'Pass TD', points: 4 },
      { key: 'pass_int', label: 'Interception', points: -2 },
      { key: 'rush_yds', label: 'Rush Yds', points: 0.1 },
      { key: 'rush_td', label: 'Rush TD', points: 6 },
      { key: 'rec', label: 'Reception (PPR)', points: 1 },
      { key: 'rec_yds', label: 'Rec Yds', points: 0.1 },
      { key: 'rec_td', label: 'Rec TD', points: 6 },
      { key: 'fum_lost', label: 'Fumble Lost', points: -2 },
    ],
  },
  {
    sport: 'NBA',
    lineupFrequency: 'daily',
    scoringType: 'points',
    hasIR: true,
    hasTaxi: false,
    hasBye: false,
    maxRosterSize: 13,
    defaultPositions: [
      { slot: 'PG', eligible: ['PG'], count: 1 },
      { slot: 'SG', eligible: ['SG'], count: 1 },
      { slot: 'SF', eligible: ['SF'], count: 1 },
      { slot: 'PF', eligible: ['PF'], count: 1 },
      { slot: 'C', eligible: ['C'], count: 1 },
      { slot: 'G', eligible: ['PG', 'SG'], count: 1 },
      { slot: 'F', eligible: ['SF', 'PF'], count: 1 },
      { slot: 'UTIL', eligible: ['*'], count: 1 },
      { slot: 'BN', eligible: ['*'], count: 4 },
      { slot: 'IR', eligible: ['*'], count: 1 },
    ],
    statCategories: [
      { key: 'pts', label: 'Points', points: 1 },
      { key: 'reb', label: 'Rebounds', points: 1.2 },
      { key: 'ast', label: 'Assists', points: 1.5 },
      { key: 'stl', label: 'Steals', points: 3 },
      { key: 'blk', label: 'Blocks', points: 3 },
      { key: 'to', label: 'Turnovers', points: -1 },
      { key: 'threes', label: '3-Pointers', points: 0.5 },
    ],
  },
  {
    sport: 'MLB',
    lineupFrequency: 'daily',
    scoringType: 'points',
    hasIR: true,
    hasTaxi: false,
    hasBye: false,
    maxRosterSize: 25,
    defaultPositions: [
      { slot: 'C', eligible: ['C'], count: 1 },
      { slot: '1B', eligible: ['1B'], count: 1 },
      { slot: '2B', eligible: ['2B'], count: 1 },
      { slot: '3B', eligible: ['3B'], count: 1 },
      { slot: 'SS', eligible: ['SS'], count: 1 },
      { slot: 'OF', eligible: ['OF', 'LF', 'CF', 'RF'], count: 3 },
      { slot: 'UTIL', eligible: ['*'], count: 1 },
      { slot: 'SP', eligible: ['SP'], count: 2 },
      { slot: 'RP', eligible: ['RP', 'P'], count: 2 },
      { slot: 'P', eligible: ['SP', 'RP'], count: 2 },
      { slot: 'BN', eligible: ['*'], count: 5 },
      { slot: 'IL', eligible: ['*'], count: 2 },
    ],
    statCategories: [
      { key: 'r', label: 'Runs', points: 1 },
      { key: 'hr', label: 'Home Runs', points: 4 },
      { key: 'rbi', label: 'RBI', points: 1 },
      { key: 'sb', label: 'Stolen Bases', points: 2 },
      { key: 'avg', label: 'Batting Avg', points: 0 },
      { key: 'ip', label: 'Innings Pitched', points: 2.5 },
      { key: 'so', label: 'Strikeouts', points: 1 },
      { key: 'w', label: 'Win', points: 5 },
      { key: 'sv', label: 'Save', points: 5 },
      { key: 'era', label: 'ERA', points: 0 },
      { key: 'er', label: 'Earned Runs', points: -1 },
    ],
  },
  {
    sport: 'NHL',
    lineupFrequency: 'daily',
    scoringType: 'points',
    hasIR: true,
    hasTaxi: false,
    hasBye: false,
    maxRosterSize: 16,
    defaultPositions: [
      { slot: 'C', eligible: ['C'], count: 2 },
      { slot: 'LW', eligible: ['LW', 'W'], count: 2 },
      { slot: 'RW', eligible: ['RW', 'W'], count: 2 },
      { slot: 'D', eligible: ['D'], count: 4 },
      { slot: 'G', eligible: ['G'], count: 1 },
      { slot: 'BN', eligible: ['*'], count: 4 },
      { slot: 'IR', eligible: ['*'], count: 1 },
    ],
    statCategories: [
      { key: 'g', label: 'Goals', points: 3 },
      { key: 'a', label: 'Assists', points: 2 },
      { key: 'ppp', label: 'PPP', points: 1 },
      { key: 'sog', label: 'Shots on Goal', points: 0.5 },
      { key: 'hits', label: 'Hits', points: 0.5 },
      { key: 'blks', label: 'Blocks', points: 0.5 },
      { key: 'gw', label: 'Goals Against Avg', points: 0 },
      { key: 'sv_pct', label: 'Save %', points: 0 },
    ],
  },
  {
    sport: 'NCAAFB',
    lineupFrequency: 'weekly',
    scoringType: 'points',
    hasIR: false,
    hasTaxi: false,
    hasBye: false,
    maxRosterSize: 18,
    defaultPositions: [
      { slot: 'QB', eligible: ['QB'], count: 1 },
      { slot: 'RB', eligible: ['RB'], count: 2 },
      { slot: 'WR', eligible: ['WR'], count: 2 },
      { slot: 'TE', eligible: ['TE'], count: 1 },
      { slot: 'FLEX', eligible: ['RB', 'WR', 'TE'], count: 1 },
      { slot: 'K', eligible: ['K'], count: 1 },
      { slot: 'BN', eligible: ['*'], count: 5 },
    ],
    statCategories: [
      { key: 'pass_yds', label: 'Pass Yds', points: 0.04 },
      { key: 'pass_td', label: 'Pass TD', points: 4 },
      { key: 'rush_yds', label: 'Rush Yds', points: 0.1 },
      { key: 'rush_td', label: 'Rush TD', points: 6 },
      { key: 'rec', label: 'Reception', points: 1 },
      { key: 'rec_yds', label: 'Rec Yds', points: 0.1 },
      { key: 'rec_td', label: 'Rec TD', points: 6 },
    ],
  },
  {
    sport: 'NCAABB',
    lineupFrequency: 'daily',
    scoringType: 'points',
    hasIR: false,
    hasTaxi: false,
    hasBye: false,
    maxRosterSize: 10,
    defaultPositions: [
      { slot: 'PG', eligible: ['PG'], count: 1 },
      { slot: 'SG', eligible: ['SG'], count: 1 },
      { slot: 'SF', eligible: ['SF'], count: 1 },
      { slot: 'PF', eligible: ['PF'], count: 1 },
      { slot: 'C', eligible: ['C'], count: 1 },
      { slot: 'UTIL', eligible: ['*'], count: 2 },
      { slot: 'BN', eligible: ['*'], count: 3 },
    ],
    statCategories: [
      { key: 'pts', label: 'Points', points: 1 },
      { key: 'reb', label: 'Rebounds', points: 1.2 },
      { key: 'ast', label: 'Assists', points: 1.5 },
      { key: 'stl', label: 'Steals', points: 3 },
      { key: 'blk', label: 'Blocks', points: 3 },
      { key: 'to', label: 'Turnovers', points: -1 },
    ],
  },
  {
    sport: 'SOCCER',
    lineupFrequency: 'per_match',
    scoringType: 'points',
    hasIR: false,
    hasTaxi: false,
    hasBye: false,
    maxRosterSize: 15,
    defaultPositions: [
      { slot: 'GK', eligible: ['GK'], count: 1 },
      { slot: 'DEF', eligible: ['DEF', 'D'], count: 4 },
      { slot: 'MID', eligible: ['MID', 'M'], count: 4 },
      { slot: 'FWD', eligible: ['FWD', 'F'], count: 2 },
      { slot: 'BN', eligible: ['*'], count: 4 },
    ],
    statCategories: [
      { key: 'goals', label: 'Goals', points: 6 },
      { key: 'assists', label: 'Assists', points: 3 },
      { key: 'clean_sheet_def', label: 'Clean Sheet (DEF)', points: 4 },
      { key: 'clean_sheet_gk', label: 'Clean Sheet (GK)', points: 4 },
      { key: 'saves', label: 'Saves', points: 0.5 },
      { key: 'yellow_card', label: 'Yellow Card', points: -1 },
      { key: 'red_card', label: 'Red Card', points: -3 },
      { key: 'own_goal', label: 'Own Goal', points: -2 },
      { key: 'pen_miss', label: 'Penalty Miss', points: -2 },
      { key: 'pen_save', label: 'Penalty Save (GK)', points: 5 },
    ],
  },
]

export async function seedSportConfigs(prisma: PrismaClient) {
  for (const c of CONFIGS) {
    await prisma.sportConfig.upsert({
      where: { sport: c.sport },
      create: {
        sport: c.sport,
        lineupFrequency: c.lineupFrequency,
        scoringType: c.scoringType,
        hasIR: c.hasIR,
        hasTaxi: c.hasTaxi,
        hasBye: c.hasBye,
        maxRosterSize: c.maxRosterSize,
        defaultPositions: c.defaultPositions,
        statCategories: c.statCategories,
      },
      update: {
        lineupFrequency: c.lineupFrequency,
        scoringType: c.scoringType,
        hasIR: c.hasIR,
        hasTaxi: c.hasTaxi,
        hasBye: c.hasBye,
        maxRosterSize: c.maxRosterSize,
        defaultPositions: c.defaultPositions,
        statCategories: c.statCategories,
      },
    })
  }
}
