import type { PrismaClient } from '@prisma/client'

const STANDARD_20_ARC_STEPS = [
  {
    week: 0,
    phase: 'pre_draft',
    events: ['fantasy_draft'],
    aiActions: ['post_welcome_message', 'announce_tribe_formation'],
    twists: [],
    notes:
      'Draft completes. Tribes auto-assigned. Idols seeded privately after draft.',
  },
  {
    week: 1,
    phase: 'pre_merge',
    events: ['tribe_scoring', 'opening_challenge'],
    aiActions: ['post_tribal_intro', 'run_challenge', 'announce_tribe_scores', 'open_tribal'],
    tribal: { count: 1, target: 'lowest_score_tribe' },
    elimination: { count: 1 },
    challenge: { type: 'sports_prediction', scope: 'tribe', reward: 'immunity_bonus' },
    twists: [],
    notes: 'First elimination. No idols expected to play yet. Establish tone.',
    recommendedFirstElimination: true,
  },
  {
    week: 2,
    phase: 'pre_merge',
    events: ['tribe_scoring', 'challenge'],
    aiActions: ['weekly_recap', 'challenge_post', 'tribal_council'],
    tribal: { count: 1, target: 'lowest_score_tribe' },
    elimination: { count: 1 },
    challenge: { type: 'more_less_stat', scope: 'tribe', reward: 'faab' },
    twists: [],
    notes: 'Second elimination. Social dynamics forming.',
  },
  {
    week: 3,
    phase: 'pre_merge',
    events: ['tribe_scoring', 'challenge', 'potential_first_idol_play'],
    tribal: { count: 1 },
    elimination: { count: 1 },
    challenge: { type: 'tribe_total_goal', reward: 'tribe_power' },
    twists: ['first_tribe_power_available'],
    notes: 'FIRST idol may matter here. First tribe power as challenge reward.',
    recommendedFirstIdolImpact: true,
  },
  {
    week: 4,
    phase: 'pre_merge',
    events: ['tribe_scoring', 'challenge', 'tribe_swap'],
    tribal: { count: 1 },
    elimination: { count: 1 },
    challenge: { type: 'strategy_riddle', scope: 'tribe' },
    twists: ['tribe_swap'],
    swap: { trigger: 'week', targetPlayerCount: 15 },
    notes: 'FIRST TRIBE SWAP. Recommended at ~15 players remaining.',
    recommendedFirstSwap: true,
  },
  {
    week: 5,
    phase: 'pre_merge',
    events: ['tribe_scoring', 'idol_clue_week', 'challenge'],
    tribal: { count: 1 },
    elimination: { count: 1 },
    challenge: { type: 'anytime_scorer', reward: 'idol_clue' },
    twists: ['idol_clue_available'],
    notes: 'Idol clue week — challenge winner gets a private idol clue. Builds suspense.',
  },
  {
    week: 6,
    phase: 'pre_merge',
    events: ['tribe_scoring', 'challenge', 'exile_rescue_possible'],
    tribal: { count: 1 },
    elimination: { count: 1 },
    challenge: { type: 'boat_trip_exile_task', reward: 'token_bonus' },
    twists: ['exile_activity_peak'],
    notes: 'Exile players now competing for return eligibility. 4-5 players in exile by now.',
  },
  {
    week: 7,
    phase: 'pre_merge',
    events: ['merge_trigger_check', 'tribe_scoring_last', 'merge_challenge'],
    tribal: { count: 0 },
    elimination: { count: 0 },
    twists: ['merge'],
    merge: { trigger: 'player_count', targetCount: 10 },
    notes: 'MERGE WEEK. No elimination at merge. Merge celebration. All pre-merge idols expire.',
    recommendedMerge: true,
  },
  {
    week: 8,
    phase: 'post_merge',
    events: ['individual_scoring', 'individual_immunity_challenge', 'tribal_council'],
    tribal: { count: 1, target: 'all_non_immune_players' },
    elimination: { count: 1 },
    juryStart: true,
    challenge: { type: 'top_scorer_immunity', scope: 'individual' },
    twists: [],
    notes: 'FIRST POST-MERGE TRIBAL. First jury member. Individual game begins.',
  },
  { week: 9, phase: 'post_merge', events: ['individual_scoring', 'immunity_challenge', 'tribal_council'], tribal: { count: 1, perWeek: true }, elimination: { count: 1, perWeek: true }, challenge: { type: 'post_merge_variety', scope: 'individual' }, notes: 'Jury grows.' },
  { week: 10, phase: 'post_merge', events: ['individual_scoring', 'immunity_challenge', 'tribal_council'], tribal: { count: 1, perWeek: true }, elimination: { count: 1, perWeek: true }, challenge: { type: 'post_merge_variety', scope: 'individual' }, notes: 'Power plays, endgame alliances.' },
  { week: 11, phase: 'post_merge', events: ['individual_scoring', 'immunity_challenge', 'tribal_council'], tribal: { count: 1, perWeek: true }, elimination: { count: 1, perWeek: true }, challenge: { type: 'post_merge_variety', scope: 'individual' }, notes: 'Watch for idol plays.' },
  {
    week: 12,
    phase: 'post_merge',
    events: ['final_5_individual_immunity', 'tribal'],
    tribal: { count: 1 },
    notes: 'Final 5. No new powers seeded from this point forward.',
    endgamePowerLock: true,
  },
  {
    week: 13,
    phase: 'post_merge',
    events: ['final_4_individual_immunity', 'tribal'],
    tribal: { count: 1 },
    notes: 'Final 4. Last chance for any endgame idol plays.',
  },
  {
    week: 14,
    phase: 'finale',
    events: ['finalist_speeches', 'jury_questions', 'jury_voting', 'winner_reveal'],
    tribal: { count: 0 },
    notes: 'Final 3 face jury. No twists. Clean vote. Sole Survivor crowned.',
  },
]

export async function seedSurvivorSeasonArc(prisma: PrismaClient): Promise<void> {
  await prisma.survivorSeasonArcTemplate.upsert({
    where: { name: 'Standard 20-Player Season' },
    create: {
      name: 'Standard 20-Player Season',
      playerCount: 20,
      tribeCount: 4,
      description:
        'Reference arc for 20 players / 4 tribes — merge ~week 7, finale ~week 14. Tune per league.',
      arcSteps: STANDARD_20_ARC_STEPS as object,
    },
    update: {
      playerCount: 20,
      tribeCount: 4,
      description:
        'Reference arc for 20 players / 4 tribes — merge ~week 7, finale ~week 14. Tune per league.',
      arcSteps: STANDARD_20_ARC_STEPS as object,
    },
  })
}
