import type { Prisma, PrismaClient } from '@prisma/client'

type Row = Prisma.SurvivorChallengeTemplateCreateInput

const D: Partial<Row> = {
  scope: 'tribe',
  submissionChannel: 'tribe_chat',
  deadlineBehavior: '',
  tiebreakerRule: '',
  defaultRewardType: '',
  affectsImmunity: false,
  affectsFaab: false,
  grantsIdol: false,
  grantsDisadvantage: false,
  aiCanAutoGenerate: true,
  commissionerApprovalRecommended: false,
  phaseValidity: 'pre_merge',
}

export const SURVIVOR_CHALLENGE_TEMPLATE_ROWS: Row[] = [
  {
    ...D,
    challengeKey: 'winner_pick',
    name: 'Win Predictor',
    theme: 'Pick the winner of a specific game this week',
    category: 'sports_prediction',
    inputDescription:
      'Each tribe submits one team they predict will win. All members must agree (tribe consensus).',
    deadlineBehavior: 'Locks at kickoff of the chosen game',
    tiebreakerRule: 'If both tribes correct: tribe with highest weekly fantasy score wins',
    defaultRewardType: 'immunity_bonus',
    affectsImmunity: true,
    sportAdaptation: {
      NFL: 'Pick MNF/SNF/TNF winner',
      NBA: 'Pick the higher-scoring team in a marquee game',
      MLB: 'Pick winner of a weekend series game',
      NHL: 'Pick regulation winner of a featured game',
      NCAAFB: 'Pick the ranked team winner',
      NCAABB: 'Pick upset or favorite in a conference game',
      SOCCER: 'Pick the match result: home/draw/away',
    },
  },
  {
    ...D,
    challengeKey: 'combined_score_over_under',
    name: 'Score Oracle',
    theme: 'Predict combined points total over/under',
    category: 'sports_prediction',
    inputDescription:
      'Each tribe submits OVER or UNDER for a specific game\'s combined score. AI sets the line.',
    tiebreakerRule:
      'If both correct: closest estimate if decimal picked, else coin flip',
    defaultRewardType: 'faab',
  },
  {
    ...D,
    challengeKey: 'anytime_scorer_pick',
    name: 'Score First',
    theme: 'Pick a player to score at any point during a game',
    category: 'sports_prediction',
    scope: 'individual',
    submissionChannel: 'private_chimmy',
    inputDescription:
      'Each player privately picks one player who will score (TD/goal/basket) anytime in a game.',
    defaultRewardType: 'points',
  },
  {
    ...D,
    challengeKey: 'more_less_stat',
    name: 'Stat Duel',
    theme: 'Pick more or less on a specific player\'s stat line',
    category: 'sports_prediction',
    inputDescription:
      'AI sets a stat line (e.g., QB passing yards). Tribe picks MORE or LESS. AI sets the threshold.',
    defaultRewardType: 'challenge_tiebreak_advantage',
  },
  {
    ...D,
    challengeKey: 'exact_score_proximity',
    name: 'Dead-On',
    theme: 'Predict exact final score — closest wins',
    category: 'sports_prediction',
    inputDescription:
      'Each tribe submits their predicted final score for a game. Closest to exact total wins.',
    tiebreakerRule: 'If same total distance: tie resolved by tribal fantasy score',
    defaultRewardType: 'immunity_bonus',
    affectsImmunity: true,
  },
  {
    ...D,
    challengeKey: 'highest_stat_position',
    name: 'Positional Domination',
    theme: 'Which position will have the highest total fantasy points this week?',
    category: 'sports_prediction',
    inputDescription:
      'Each tribe submits one position (QB/RB/WR/TE). Tribe whose position had highest average points wins.',
    defaultRewardType: 'tribe_power',
  },
  {
    ...D,
    challengeKey: 'player_prop_challenge',
    name: 'Prop Master',
    theme: 'Player-specific prop prediction',
    category: 'sports_prediction',
    inputDescription:
      'Each tribe picks one player and one stat. If that player hits the stat threshold, tribe earns reward.',
    defaultRewardType: 'faab',
  },
  {
    ...D,
    challengeKey: 'combined_tribe_predictions',
    name: 'Tribal Oracle',
    theme: 'Combine tribe members\' individual predictions — majority wins',
    category: 'sports_prediction',
    submissionChannel: 'private_chimmy',
    inputDescription:
      'Each tribe member privately submits a pick. Tribe\'s result is the majority answer. AI tallies privately.',
    defaultRewardType: 'idol_clue',
  },
  {
    ...D,
    challengeKey: 'tribe_consensus',
    name: 'Tribe Unity',
    theme: 'All tribe members must submit the same answer',
    category: 'strategy_social',
    submissionChannel: 'private_chimmy',
    inputDescription:
      'Each member submits independently to @Chimmy. If all match: tribe wins. If any differ: tribe loses.',
    tiebreakerRule: 'N/A — either all match or they don\'t',
    defaultRewardType: 'safety_without_power_clue',
    grantsDisadvantage: true,
    commissionerApprovalRecommended: true,
  },
  {
    ...D,
    challengeKey: 'sacrifice_challenge',
    name: 'Who Volunteers?',
    theme: 'One tribe member must voluntarily sit out — and earns a hidden reward',
    category: 'strategy_social',
    submissionChannel: 'private_chimmy',
    inputDescription:
      'One tribe member tells @Chimmy they are sitting out. If nobody volunteers in 1 hour: random person is selected.',
    defaultRewardType: 'secret_advantage',
    grantsIdol: true,
    aiCanAutoGenerate: false,
    commissionerApprovalRecommended: true,
    notes:
      'The sacrifice player secretly receives an advantage. Creates deception opportunities.',
  },
  {
    ...D,
    challengeKey: 'hidden_saboteur',
    name: 'Among Us',
    theme: 'One player secretly tries to make the tribe lose',
    category: 'strategy_social',
    submissionChannel: 'private_chimmy',
    aiCanAutoGenerate: false,
    commissionerApprovalRecommended: true,
    defaultRewardType: 'token',
    inputDescription:
      'AI privately assigns one member the saboteur role. Saboteur submits a WRONG answer. Other members must submit a correct prediction.',
  },
  {
    ...D,
    challengeKey: 'trust_challenge',
    name: 'Blind Trust',
    theme: 'Tribe must submit ONE answer chosen by a randomly selected leader',
    category: 'strategy_social',
    submissionChannel: 'private_chimmy',
    defaultRewardType: 'faab',
    inputDescription:
      'AI selects one tribe member as leader (secret). Leader picks the answer. Tribe cannot discuss — answer is locked.',
  },
  {
    ...D,
    challengeKey: 'sit_out_decision',
    name: 'Step Down',
    theme: 'Tribe must decide who sits out — and that person receives unknown consequence',
    category: 'strategy_social',
    defaultRewardType: 'random_reward_or_penalty',
    grantsDisadvantage: true,
    aiCanAutoGenerate: false,
    commissionerApprovalRecommended: true,
    inputDescription:
      'Tribe names who sits out in tribe chat. Sat-out player may receive reward or penalty (AI randomizes, commissioner-configurable).',
  },
  {
    ...D,
    challengeKey: 'halftime_puzzle',
    name: 'Halftime Brain',
    theme: 'Answer a multi-part puzzle at halftime of a featured game',
    category: 'puzzle_riddle',
    deadlineBehavior: '20 minutes after halftime post',
    tiebreakerRule: 'Fastest correct answer wins if tied',
    defaultRewardType: 'challenge_safety',
    inputDescription: 'AI posts puzzle at halftime. Tribe has 20 minutes to submit. First correct answer wins.',
  },
  {
    ...D,
    challengeKey: 'survivor_trivia',
    name: 'Island Knowledge',
    theme: 'Trivia questions about this season\'s events so far',
    category: 'puzzle_riddle',
    defaultRewardType: 'tribe_power',
    inputDescription:
      '5 questions about this specific league\'s season events. Tribe submits answers in tribe chat.',
    notes: 'AI generates questions based on actual game history (votes, scores, eliminations)',
  },
  {
    ...D,
    challengeKey: 'hidden_phrase',
    name: 'Decode It',
    theme: 'Decode a hidden phrase from clues posted in league chat over 3 days',
    category: 'puzzle_riddle',
    deadlineBehavior: '72 hours from first clue',
    defaultRewardType: 'idol_clue',
    inputDescription: 'AI drops one clue per day in league chat (3 clues). Tribe submits decoded phrase on Day 4.',
  },
  {
    ...D,
    challengeKey: 'logo_symbol_challenge',
    name: 'Tribal Emblem',
    theme: 'Identify which team/player/stat a custom AI-generated logo represents',
    category: 'puzzle_riddle',
    defaultRewardType: 'faab',
    inputDescription: 'AI generates a visual riddle (emoji-based in chat). Tribe submits their guess.',
  },
  {
    ...D,
    challengeKey: 'faab_auction',
    name: 'Open Market',
    theme: 'Mini FAAB auction for challenge reward',
    category: 'resource',
    scope: 'league_wide',
    submissionChannel: 'private_chimmy',
    affectsFaab: true,
    aiCanAutoGenerate: false,
    commissionerApprovalRecommended: true,
    defaultRewardType: 'varies',
    inputDescription:
      'AI posts 3 items (immunity boost, extra FAAB, idol clue). Each player bids FAAB privately. Highest bidder per item wins.',
  },
  {
    ...D,
    challengeKey: 'token_earning_challenge',
    name: 'Token Run',
    theme: 'Exile-style token earning for main island players',
    category: 'resource',
    inputDescription:
      'Pick one player to invest in. If that player scores above league average this week, tribe earns 1 token each.',
    defaultRewardType: 'token',
  },
  {
    ...D,
    challengeKey: 'tribe_stash_challenge',
    name: 'Stash It',
    theme: 'Tribe earns a hidden item by completing a streak challenge',
    category: 'resource',
    deadlineBehavior: '2-week rolling window',
    grantsIdol: true,
    commissionerApprovalRecommended: true,
    inputDescription:
      'Tribe must score above a threshold for 2 consecutive weeks. If they do: stash is unlocked. Stash contains a random power.',
  },
  // Post-merge
  {
    ...D,
    challengeKey: 'top_scorer_immunity',
    name: 'Top of the Island',
    theme: 'Highest weekly fantasy scorer wins individual immunity',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    inputDescription: 'No submission needed. Automatic from weekly fantasy scores.',
    defaultRewardType: 'immunity',
    affectsImmunity: true,
  },
  {
    ...D,
    challengeKey: 'exact_score_individual',
    name: 'Oracle\'s Eye',
    theme: 'Individual exact score prediction — closest wins immunity',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    submissionChannel: 'private_chimmy',
    tiebreakerRule: 'Over-prediction beats under-prediction if equal distance',
    defaultRewardType: 'immunity',
    affectsImmunity: true,
    inputDescription: 'Each player privately submits expected total fantasy score for themselves this week.',
  },
  {
    ...D,
    challengeKey: 'immunity_clue_challenge',
    name: 'The Clue',
    theme: 'Win the challenge, receive a clue to a hidden merge immunity idol',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    defaultRewardType: 'idol_clue',
    inputDescription: 'Any challenge format. Winner gets a private idol clue from @Chimmy.',
  },
  {
    ...D,
    challengeKey: 'choose_safety_or_power',
    name: 'Temptation',
    theme: 'Choose: take immunity OR take a secret advantage',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    submissionChannel: 'private_chimmy',
    affectsImmunity: true,
    grantsIdol: true,
    aiCanAutoGenerate: false,
    commissionerApprovalRecommended: true,
    inputDescription:
      'After a challenge qualifier, top player chooses Safety (immunity) or Power (secret advantage). Decision is private.',
  },
  {
    ...D,
    challengeKey: 'private_bonus_pick',
    name: 'Side Hustle',
    theme: 'Private submission for bonus fantasy points this week',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    submissionChannel: 'private_chimmy',
    defaultRewardType: 'points',
    inputDescription:
      'Each player submits one bonus player prediction to @Chimmy. If that player outscores their projection: +5 points.',
  },
  {
    ...D,
    challengeKey: 'winner_score_combo',
    name: 'Perfect Combo',
    theme: 'Pick a game winner AND a total score — both must be right',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    submissionChannel: 'private_chimmy',
    tiebreakerRule: 'First submission timestamp',
    defaultRewardType: 'immunity',
    affectsImmunity: true,
    inputDescription: 'Submit game winner + exact final score. Must get both correct. First correct wins immunity.',
  },
  {
    ...D,
    challengeKey: 'secret_box_hidden_power',
    name: 'The Hidden Box',
    theme: 'Random player receives a secret box — open it or sell it',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    submissionChannel: 'private_chimmy',
    grantsIdol: true,
    grantsDisadvantage: true,
    aiCanAutoGenerate: false,
    commissionerApprovalRecommended: true,
    inputDescription:
      'AI privately notifies one random player they have a box. They choose to open (random power or penalty) or sell (FAAB) within 24 hours.',
  },
  {
    ...D,
    challengeKey: 'exile_rescue_challenge',
    name: 'Island SOS',
    theme: 'Active players compete to earn a token that helps an exile player',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    defaultRewardType: 'token',
    inputDescription:
      'Individual prediction challenge. Winner earns +2 tokens credited to the exile player of their choice.',
  },
  {
    ...D,
    challengeKey: 'public_temptation_auction',
    name: 'The Auction',
    theme: 'Open auction for 3 items with unknown contents',
    category: 'post_merge',
    scope: 'league_wide',
    phaseValidity: 'post_merge',
    affectsFaab: true,
    grantsIdol: true,
    aiCanAutoGenerate: false,
    commissionerApprovalRecommended: true,
    defaultRewardType: 'varies',
    inputDescription: '3 mystery items. Players bid FAAB. Highest bidder per item wins. AI reveals contents after bids close.',
  },
  {
    ...D,
    challengeKey: 'immunity_plus_penalty',
    name: 'Price of Safety',
    theme: 'Win immunity, but accept a penalty that will affect you NEXT week',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    affectsImmunity: true,
    grantsDisadvantage: true,
    inputDescription:
      'Automatic: highest scorer wins immunity AND receives a disadvantage for next week.',
    notes: 'Creates tension — is this week\'s safety worth next week\'s disadvantage?',
  },
  {
    ...D,
    challengeKey: 'stat_race',
    name: 'Stat Race',
    theme: 'First player to reach a cumulative stat target wins reward',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    defaultRewardType: 'faab',
    inputDescription:
      'AI sets a cumulative stat target for the week. First player whose lineup hits the target wins the FAAB reward.',
  },
  {
    ...D,
    challengeKey: 'jury_watch',
    name: 'Jury\'s Eye',
    theme: 'Jury votes for which active player had the best week — that player earns a reward',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    defaultRewardType: 'immunity_clue',
    aiCanAutoGenerate: false,
    commissionerApprovalRecommended: true,
    inputDescription:
      'Jury members vote privately for the active player they think had the best week. Plurality wins; winner receives an immunity clue.',
  },
  {
    ...D,
    challengeKey: 'reverse_immunity',
    name: 'Flip It',
    theme: 'Worst fantasy scorer wins immunity — protects the weakest player',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    affectsImmunity: true,
    inputDescription:
      'No pick required. Lowest weekly fantasy scorer among eligible players wins individual immunity.',
    notes: 'Strategic: do you play poorly to win immunity?',
  },
  {
    ...D,
    challengeKey: 'alliance_pledge',
    name: 'Public Pledge',
    theme: 'Announce a 2-person alliance publicly — both are safe for ONE week',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    affectsImmunity: true,
    aiCanAutoGenerate: false,
    commissionerApprovalRecommended: true,
    inputDescription:
      'Two players post a public pledge in league chat naming each other. Both are immune from votes for exactly one Tribal Council.',
  },
  {
    ...D,
    challengeKey: 'final_challenge_gauntlet',
    name: 'Final Stand',
    theme: '3-part challenge on Final 4 week. Winner is guaranteed Final 3.',
    category: 'post_merge',
    scope: 'individual',
    phaseValidity: 'post_merge',
    affectsImmunity: true,
    inputDescription:
      'Three sequential legs (e.g. prediction, puzzle, lineup). Highest combined score wins immunity into Final 3.',
    notes: 'Used only on Final 4 week',
  },
  // Exile
  {
    ...D,
    challengeKey: 'exile_weekly_lineup',
    name: 'Exile Lineup',
    theme: 'Build a lineup from a fixed player pool available on exile',
    category: 'exile',
    scope: 'exile',
    phaseValidity: 'exile',
    submissionChannel: 'private_chimmy',
    inputDescription:
      'AI provides a pool of 20 players (same sport). Each exile player picks their starting lineup from this pool. Best score wins the week\'s token.',
    extraMetadata: { tokenValue: 1 },
    notes: 'Fresh pool each week. No carryover from main island rosters.',
  },
  {
    ...D,
    challengeKey: 'exile_pickem',
    name: 'Exile Pick\'Em',
    theme: 'Simple weekly pick\'em — correct picks earn tokens',
    category: 'exile',
    scope: 'exile',
    phaseValidity: 'exile',
    inputDescription:
      '3-5 picks (game winners, score results). Each correct pick = 1 token. AI generates picks from current week\'s schedule.',
    extraMetadata: { tokenValue: 1 },
  },
  {
    ...D,
    challengeKey: 'exile_stat_target',
    name: 'Stat Hunt',
    theme: 'Pick one player to hit a specific stat threshold',
    category: 'exile',
    scope: 'exile',
    phaseValidity: 'exile',
    inputDescription:
      'Pick one player. If that player hits AI-set stat threshold (e.g., 25+ fantasy points): earn 2 tokens.',
    extraMetadata: { tokenValue: 2 },
  },
  {
    ...D,
    challengeKey: 'exile_boss_fight',
    name: 'Beat the Boss',
    theme: 'Exile players compete against the Boss\'s auto-lineup',
    category: 'exile',
    scope: 'exile',
    phaseValidity: 'exile',
    inputDescription:
      'Boss has a preset lineup (commissioner-set or AI-set). Exile players must collectively outscore the Boss total. If even one exile player beats Boss: that player earns a token.',
    extraMetadata: { tokenValue: 1 },
    notes: 'If Boss wins: all exile token balances reset to 0 (if commissioner enables boss reset)',
  },
  {
    ...D,
    challengeKey: 'exile_survivor_trivia',
    name: 'Exile Lore',
    theme: 'Trivia about the main island season — exile players may know things main island players don\'t',
    category: 'exile',
    scope: 'exile',
    phaseValidity: 'exile',
    inputDescription:
      '5 trivia questions about the season\'s early events. Highest score earns token.',
    extraMetadata: { tokenValue: 1 },
  },
  {
    ...D,
    challengeKey: 'exile_return_qualifier',
    name: 'Return Challenge',
    theme: 'Head-to-head competition between exile players for re-entry',
    category: 'exile',
    scope: 'exile',
    phaseValidity: 'exile',
    defaultRewardType: 'main_island_return',
    extraMetadata: { tokenValue: 0 },
    commissionerApprovalRecommended: true,
    inputDescription:
      'One-week high-stakes challenge. Top exile scorer or challenge winner earns the return slot. All exile players compete.',
    notes: 'One-time event. Triggered by commissioner or automatic at configured week.',
  },
  {
    ...D,
    challengeKey: 'exile_anytime_scorer',
    name: 'Exile Anytime',
    theme: 'Pick one player to score at any point — same as main island version',
    category: 'exile',
    scope: 'exile',
    phaseValidity: 'exile',
    submissionChannel: 'private_chimmy',
    inputDescription: 'Pick to @Chimmy. If player scores: earn 1 token.',
    extraMetadata: { tokenValue: 1 },
  },
  {
    ...D,
    challengeKey: 'exile_sacrifice_bet',
    name: 'All In',
    theme: 'Wager tokens on a prediction — win or lose big',
    category: 'exile',
    scope: 'exile',
    phaseValidity: 'exile',
    submissionChannel: 'private_chimmy',
    inputDescription:
      'Player tells @Chimmy how many tokens they wager (1-3). Makes one prediction. Correct = tokens doubled. Wrong = tokens lost.',
    extraMetadata: { tokenValue: 'variable' },
    notes: 'Commissioner must enable harsh mode for token loss. Default: tokens lost only, no gain if incorrect.',
  },
]

export async function seedSurvivorChallengeTemplates(prisma: PrismaClient): Promise<void> {
  for (const row of SURVIVOR_CHALLENGE_TEMPLATE_ROWS) {
    await prisma.survivorChallengeTemplate.upsert({
      where: { challengeKey: row.challengeKey },
      create: row,
      update: row,
    })
  }
}
